#! /bin/bash
#
# Generated by the utility: /z/tools/collect_git_checked_out_branch_recusively.sh 
#
# Checkout each git repository to the given branch/commit or list them
#

mode=h;
while getopts ":hlrc" opt ; do
  #echo opt+arg = "$opt$OPTARG"
  case "$opt$OPTARG" in
  l )
    mode=l;
    ;;

  c )
    mode=c;
    ;;

  r )
    mode=r;
    ;;

  * )
    ;;
  esac
done

if test "$mode" = "h" ; then
  cat <<EOH
checkout_to_known_git_branches_recursive.sh options

Options:

-h      : print this help
-l      : LIST the branch/commit for each git repository (directory) registered in this script.
-c      : CHECKOUT each git repository to the BRANCH registered in this script.
-r      : CHECKOUT/REVERT each git repository to the COMMIT registered in this script.

Note:

Use the '-r' option to set each repository to an exact commit position, which is useful if,
for instance, you wish to reproduce this registered previous software state (which may
represent a software release) which you wish to analyze/debug.

EOH
  exit 1;
fi

if test "$mode" = "l" ; then
  cat <<EOH

Git repository directory                    :: commit hash                         / branch name
--------------------------------------------::--------------------------------------------------
EOH
fi



# args: DIR COMMIT [BRANCH]
git_repo_checkout_branch() {
  if test "$mode" = "c" || test "$mode" = "r" ; then
    if test -d "$1" ; then
      pushd "$1"                                                               2> /dev/null  > /dev/null
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
      if test "$mode" = "c" ; then
        if test -n "$3" ; then
          # make sure the branch is created locally and is a tracking branch, if it isn't already:
          # https://www.cyberciti.biz/faq/bash-remove-whitespace-from-string/
          current_branch=$( git branch --show-current )
          if test -z "$current_branch" -o "$current_branch" != "$3" ; then
            git checkout "$3"
          fi

          shopt -s extglob
          remote_branch=$( git branch -vv --list $3 '--format=%(upstream)' )
          # Trim leading whitespaces
          remote_branch="${remote_branch##*( )}"
          # Trim trailing whitespaces
          remote_branch="${remote_branch%%*( )}"
          echo "=${remote_branch}="
          shopt -u extglob

          if test -z "$remote_branch" ; then
            echo "No remote branch registered for local branch: $3 --> setting up the remote."
            git branch --track "$3" "remotes/origin/$3"                          2> /dev/null  > /dev/null
            git branch --set-upstream-to=remotes/origin/$3 $3                    2> /dev/null  > /dev/null
            git checkout "$3"
          fi
        else
          current_branch=$( git branch --show-current )
          echo "=${current_branch}="
          if test -z "$current_branch" -o "$current_branch" != "master" ; then
            # checkout to the first of `master` or `main` in case we're not checked out to either right now:
            if test "$current_branch" != "main" -a "$current_branch" != "master" ; then
              echo "Checking out to master/main:"
              git checkout master
              if test $? -ne 0 ; then
                git checkout main
              fi
            fi
          fi
        fi
      else
        git checkout "$2"
      fi
      popd                                                                     2> /dev/null  > /dev/null
    fi
  else
    if test -d "$1" ; then
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
    else
      printf "%-43s :: %s / %s\n" "[DIRECTORY DOES NOT EXIST!] $1" "$2" "$3"
    fi
  fi
}


#
# Make sure we switch to the utility directory as all the relative paths for the repositories
# are based off that path!
#
pushd $(dirname $0)                                                            2> /dev/null  > /dev/null



#
# The registered repositories:
#

git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/1D-RGB-color-gradient" 47c5b0ea18263238d28d4800dbc7fa5981c2d4fd main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/2D-color-gradient-or-Procedural-texture" b3d8e9dd2d7e738ea30604085469307444ed0356 main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/ADE-graph-management" 0e8a2ccdd34f29dba55894f5f3c5179809888b9e master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/AFLplusplus" 775861ea94d00672c9e868db329073afd699b994 stable    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/A-MNS_TemplateMatching" de87d7364658282d6dec104c72cfff4727520e9c main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/ApprovalTestsCpp" 9dbebe9e06f156401ccbdc2bb1c5fac96ecad225 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/ArborX" 3080e6b728e7b49d60160a8c598ca3d9c1b3d378 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BaseMatrixOps" 9e5beec15d803f0429dadae5e9218ef907271383 main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BayerToRGB" 902e3a40fbd72f9aaf7eae3ed48311d70f977f9f master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BBHash" 9134394c15942ea90b3c6b5fdb61314633de9ff5 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BCF-cuckoo-index" 8918ebadc951d956930ba3a62d4d99b262d0caac master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Bi-Sent2Vec" b3bf758f86a7006112a7a65bf9955d88ef3465d7 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BitFunnel" b8ec70eeb3aa2f6aef6166feb6780fac3acf981b master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BLAKE3" 0b5b6fab7acf49def02f533ff6573ff389205c2a master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BlingFire" 3a8d44a168c0b8cf2ba1e1e8a5e25e4646a838e7 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BoxFort" c91d7181734ab2fd6d1299e8aa927297f0ddb754 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CacheLib" 4138001686a20c303a386bf2c272d360c37e284b main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CacheLib/cachelib/external/fbthrift" f6681150810835c02e9c1efd1ec8f5d615c51618           
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CacheLib/cachelib/external/fizz" f1ff66035720aee4983b330201956abf0dbb9dfa           
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CacheLib/cachelib/external/folly" f601d244aac60d591228cfd41a566d0039d4deef           
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CacheLib/cachelib/external/mvfst" ce9687220e47b01232d2186b610b23958009792a           
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CacheLib/cachelib/external/wangle" 0f6bdb225f0eb2a363d9171425966977c2b035d8           
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Capture2Text" adcce2467568c230411851a1cef1d3bad44a4115 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CHM-lib" e5cc1ca9e9b29afe2ebc75e38ce6aaae986c3658 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CImg" b65e4ba5bc9656a60c1aeafe4b8e86a006c751da master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CLBlast" b050a61ed98f85c9e09b9bd5c75d706a36b24cf9 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CLBlast-database" 07eec67dafdc94a58cfd4b83d145f494231e4611 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Clipper2" 775ec626dfffadb2eac88ef9e91f7ae30ab35e28 main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CLTune" 6a13b43af09bbbfd3b83223c5a1c9c57d63c0330 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Cmathtuts" a3610505e04c162c48ad8b8eab9745b32f2f0b6d master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CNTK" 10a8ffcf50d7b9225f3236ffcfdc422b2014fb92 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/ColorSpace" 2b28f91cc92d07265190c64522b4d7c5e07d09b2 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CppNumericalSolvers" 9e21e01736237a1e10e57bffca1b00fe6655d9f6 v2        
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CRFpp" 1dc92a606f874a4fe52603803364cc1d90f952fb master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CRFsuite-extended" 073d650b12460c1d6f1c3bf862e13dccaf473fc6 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Criterion" 9c01cbe75002ad8640e0f411f453fbcd0567ff79 bleeding  
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CRoaring" 29e56cde47fbab9aca71a3b0168bcfedb79381f6 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CryptSync" 1d6e4810a801d0bd527f5536aa9b0a8af1c1f267 main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CTCWordBeamSearch" 43567e5b06dd43bdcbec452f5099171c81f5e737 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CTPL-Thread-Pool" 437e135dbd94eb65b45533d9ce8ee28b5bd37b6d master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CurvatureFilter" b6697891fa853b0c2a35482e507cb7af708ce344 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CxImage" e24dc719a471f9fc6b389b84641ea065e71c9e59 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Cysboard" 387d15e72c87ac90c4760322b5db5065454ba630 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/DBoW2" 3924753db6145f12618e7de09b7e6b258db93c6e master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/DCF-cuckoo-index" f943929afe9d8f973e9f847995d9c2c2095c566c master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/DGM-CRF" 33a2e9bdaf446378ec63c10b3a07b257e32aa1ef master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Digital-Halftoning" 6da1ae6e26ce1acf9536a47652de5f4ec08c6657 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/DiskANN" 340bc58b5a776cf31c668edbc089704bc8f11c61 main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/ECMA262" c4d32f722f8231d43ba186e4191080862b1d5293 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/EigenRand" 8bc3c934af222ac8ee7baf059815d48ced550b62 main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/EtwExplorer" 9588bc5b10e33a8ad4ec56dd41edf189cbb1dad9 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Extensible-Storage-Engine" f6f66c29d191e74bc7dd1cb67cba266c6b3f255d main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FastGlobbing" 7613858a6db946ab35067a18e02d8af279b2c72c main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FastString" 7d3aa15c3cf3de06a67c299334d1c050c47dd246 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FFmpeg" 1ad7bd0fe5f9eaaf8eb9d8ab99f19a2457e3aefe master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FiberTaskingLib" 3a0566cf5e48f29e6fec5355bcd570baa30c9183 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FIt-SNE" 47ff14f1defc1ff3a8065c8b7baaf45c33e7e0b2 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FM-fast-match" 3150e54b33fa90061213a9d31e0b91445cd58433 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FreeFileSync" 23ab55b7106bb26fe3455cb2200db784966ad3fa master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/GMM-HMM-kMeans" df76ebd12cb9902705569a17a6a19f02835b8516 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/GMMreg" b18d1c9cec54ce84df950f5821b24b8e4d03d519 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/GoldFish-CBOR" 4ba6a01c7714fee78ce311ef8910f2065e80c8a5 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/GQ-gumbo-css-selectors" a00f4ed73064797c627887d5be7b8bee41d7223f master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/GraphicsMagick" a0d97e463fa59377af92f34ba86751b78f5ae1eb master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/GSL" e64c97fc2cfc11992098bb38eda932de275e3f4d main      
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/Hackers-Delight" 8b8407a7168b6e16a53b0072e48620cdb346cd76 master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/HashMap" dceb0aa92744cc7f1c76a8b86c83bf616a91739f master    
git_repo_checkout_branch "../../../../../../../../../../../../i/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/HDiffPatch" 0cbce6a4f056f88d1414be11456aa4e84d6a1bcc master    

# --- all done ---

popd                                                                           2> /dev/null  > /dev/null

