#! /bin/bash
#
# Generated by the utility: /z/tools/collect_git_checked_out_branch_recusively.sh 
#
# Checkout each git repository to the given branch/commit or list them
#

mode=h;
while getopts ":hlrc" opt ; do
  #echo opt+arg = "$opt$OPTARG"
  case "$opt$OPTARG" in
  l )
    mode=l;
    ;;

  c )
    mode=c;
    ;;

  r )
    mode=r;
    ;;

  * )
    ;;
  esac
done

if test "$mode" = "h" ; then
  cat <<EOH
checkout_to_known_git_branches_recursive.sh options

Options:

-h      : print this help
-l      : LIST the branch/commit for each git repository (directory) registered in this script.
-c      : CHECKOUT each git repository to the BRANCH registered in this script.
-r      : CHECKOUT/REVERT each git repository to the COMMIT registered in this script.

Note:

Use the '-r' option to set each repository to an exact commit position, which is useful if,
for instance, you wish to reproduce this registered previous software state (which may
represent a software release) which you wish to analyze/debug.

EOH
  exit 1;
fi

if test "$mode" = "l" ; then
  cat <<EOH

Git repository directory                    :: commit hash                         / branch name
--------------------------------------------::--------------------------------------------------
EOH
fi



# args: DIR COMMIT [BRANCH]
git_repo_checkout_branch() {
  if test "$mode" = "c" || test "$mode" = "r" ; then
    if test -d "$1" ; then
      pushd "$1"                                                               2> /dev/null  > /dev/null
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
      if test "$mode" = "c" ; then
        if test -n "$3" ; then
          # make sure the branch is created locally and is a tracking branch, if it isn't already:
          # https://www.cyberciti.biz/faq/bash-remove-whitespace-from-string/
          current_branch=$( git branch --show-current )
          if test -z "$current_branch" -o "$current_branch" != "$3" ; then
            git checkout "$3"
          fi

          shopt -s extglob
          remote_branch=$( git branch -vv --list $3 '--format=%(upstream)' )
          # Trim leading whitespaces
          remote_branch="${remote_branch##*( )}"
          # Trim trailing whitespaces
          remote_branch="${remote_branch%%*( )}"
          echo "=${remote_branch}="
          shopt -u extglob

          if test -z "$remote_branch" ; then
            echo "No remote branch registered for local branch: $3 --> setting up the remote."
            git branch --track "$3" "remotes/origin/$3"                          2> /dev/null  > /dev/null
            git branch --set-upstream-to=remotes/origin/$3 $3                    2> /dev/null  > /dev/null
            git checkout "$3"
          fi
        else
          current_branch=$( git branch --show-current )
          echo "=${current_branch}="
          if test -z "$current_branch" -o "$current_branch" != "master" ; then
            # checkout to the first of `master` or `main` in case we're not checked out to either right now:
            if test "$current_branch" != "main" -a "$current_branch" != "master" ; then
              echo "Checking out to master/main:"
              git checkout master
              if test $? -ne 0 ; then
                git checkout main
              fi
            fi
          fi
        fi
      else
        git checkout "$2"
      fi
      popd                                                                     2> /dev/null  > /dev/null
    fi
  else
    if test -d "$1" ; then
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
    else
      printf "%-43s :: %s / %s\n" "[DIRECTORY DOES NOT EXIST!] $1" "$2" "$3"
    fi
  fi
}


#
# Make sure we switch to the utility directory as all the relative paths for the repositories
# are based off that path!
#
pushd $(dirname $0)                                                            2> /dev/null  > /dev/null



#
# The registered repositories:
#

git_repo_checkout_branch "../1D-RGB-color-gradient"               7fffbc4583d0bef55e9c0d590d74ec0e899faa1f main      
git_repo_checkout_branch "../2D-color-gradient-or-Procedural-texture" 384c46ee404956883d71a19f86f365746a86eefd main      
git_repo_checkout_branch "../7zip"                                a7a1d4a241492e81f659a920f7379c193593ebc6 main      
git_repo_checkout_branch "../7-Zip-zstd"                          79b2c78e9e7735ddf90147129b75cf2797ff6522 master    
git_repo_checkout_branch "../abseil-cpp"                          86444ea9936a0c60446a4b2b2e4207de3de44528 master    
git_repo_checkout_branch "../adaptiveqf"                          089ac32c1dd5795463e1d70fc85473f93d3193c2 main      
git_repo_checkout_branch "../ADE-graph-management"                0e8a2ccdd34f29dba55894f5f3c5179809888b9e master    
git_repo_checkout_branch "../AFLplusplus"                         e7d871c8bf64962a658e447b90a1a3b43aaddc28 stable    
git_repo_checkout_branch "../agg"                                 6f5324d9ec05e78cdac77bc80eab76cde3b86a4f master    
git_repo_checkout_branch "../aho_corasick"                        b4fb360ef2764bf0cd22daaa62dd4bfd18b8ad0c master    
git_repo_checkout_branch "../aho-corasick"                        2c70bc7c2708b2670fa6f22b9fea6ee1870aac8b master    
git_repo_checkout_branch "../Allocator"                           e15fb4990c216307b6561fd4aa61328b2b7ddf4d master    
git_repo_checkout_branch "../amd-fftw"                            5a64febe99a42f6a64fd4deaa14269d02bcaf1c1 amd-fftw  
git_repo_checkout_branch "../A-MNS_TemplateMatching"              de87d7364658282d6dec104c72cfff4727520e9c main      
git_repo_checkout_branch "../annoy"                               2a948a228935f9bd0498ce4ea78ddaf1a7e0c4fa master    
git_repo_checkout_branch "../ApprovalTestsCpp"                    89636b5aecfe1ef0786a4b81075bfccae64094b5 master    
git_repo_checkout_branch "../arangodb"                            0ab82da44b767b6e7684d1b816cc456db75c2f31 devel     
git_repo_checkout_branch "../ArborX"                              c4fdba57e440b3da0b3146032d7dcdb3f20ebc3e master    
git_repo_checkout_branch "../archive-hocr-tools"                  5533a7f6bb506bbfffa459939f61137d0c9c09da master    
git_repo_checkout_branch "../argparse"                            9e19768ac89ed9eb2248a076f33a4a379f250daf master    
git_repo_checkout_branch "../armadillo"                           8b51c7072b0b3ac179e68460ffe21a5273ad09ab main      
git_repo_checkout_branch "../arrayfire"                           f4db00f2cc57272f16f0e7e8534f65c2a895cfda master    
git_repo_checkout_branch "../arrow"                               ec28590de70fc1acd815e510aa9d31e8ad414193 main      
git_repo_checkout_branch "../asio"                                2760ad12e946220429d34bc21c86ed76f3c4294c master    
git_repo_checkout_branch "../asyncplusplus"                       8585fd99a852f185cab5fdaddd9249efde7ed5c3 master    
git_repo_checkout_branch "../asynqro"                             4260820ffd790d27bdf5ed336c63ac49c742d770 develop   
git_repo_checkout_branch "../AudioFile"                           bcb61a47e64fe4e7fc3d8a8664b8a23a192bddb7 master    
git_repo_checkout_branch "../autodiff"                            4e9464524902c1401de7a2b8c096129b96ab7df6 main      
git_repo_checkout_branch "../avro"                                09910f3c97bcd51f089ba60e5ca256c1ccdc1f2b master    
git_repo_checkout_branch "../awesome-c"                           24967b00a689f91a35cdf731f988c2e67fcf85ab master    
git_repo_checkout_branch "../Awesome-Document-Image-Rectification" baf5274a54f53f1388a56bdb25a4b1f40ca41818 main      
git_repo_checkout_branch "../Awesome-Image-Quality-Assessment"    e63ac75f59eac5dbd1403c3a3e7dfb6e66250aa5 main      
git_repo_checkout_branch "../b2xtranslator"                       90d05a6589706cf177a245fcb74e9cba4b6264ae master    
git_repo_checkout_branch "../backward-cpp"                        51f0700452cf71c57d43c2d028277b24cde32502 master    
git_repo_checkout_branch "../baobzi"                              cf39a3c321aa61f63bb6d345056d7f68f0770852 main      
git_repo_checkout_branch "../BaseMatrixOps"                       9e5beec15d803f0429dadae5e9218ef907271383 main      
git_repo_checkout_branch "../basez"                               8cedfbd685f1aed8c53f5cda3fbd2798e405090e master    
git_repo_checkout_branch "../BayerToRGB"                          902e3a40fbd72f9aaf7eae3ed48311d70f977f9f master    
git_repo_checkout_branch "../bbe"                                 7c6fd66afdee54f327ea28f55bc025363723f60a master    
git_repo_checkout_branch "../BBHash"                              9134394c15942ea90b3c6b5fdb61314633de9ff5 master    
git_repo_checkout_branch "../BCF-cuckoo-index"                    9156482ee083cfbfa1add834cce1b591a6db6599 master    
git_repo_checkout_branch "../bebop"                               151fef965e2a56aafe1dc9b573488b5f9f44f9f8 master    
git_repo_checkout_branch "../bebop/docs-src"                      cb27306412af90afc64512d46e7cd15389e4fa08 master    
git_repo_checkout_branch "../BehaviorTree.CPP"                    26366ac0073a3a0de43d0d44b469255faf5e169a master    
git_repo_checkout_branch "../better-enums"                        520d8ee39037c9c94aa6e708a4fd6c0fa313ae80 master    
git_repo_checkout_branch "../bhtsne--Barnes-Hut-t-SNE"            407210c045dc932976a113fa5da6ce1c819b95b6 master    
git_repo_checkout_branch "../bibtex-robust-decoder"               7a4dcfb304dda6718c1f2c48bc313e7eeded98e0 master    
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/bkn-bibtex" a48b3fe3435aca572a2d956811b1846321d32c51 master    
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/caltechlibrary-bibtex" 3a1dc5ab3b141148e46759d8dc2f7c753e4c31f9 main      
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/digitalheir-bibliography-js" f10596c0be0cf7ae9e3e67ce6141a265f0c47e67 master    
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/jabref"  1e34797a03be3f95cfe396c95a4fc6197d20a74d           
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/orcid-bibtexParse" b55dc9e4015f9dec67921f56f8f23dadb71697ad master    
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/pcooksey-bibtex-js" 46dd3ce83cb793634b80882cb803b02a9974f106 master    
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/zekom-bibtex" 56b1da32ba1980532eafdc65248b28164f310087 master    
git_repo_checkout_branch "../bibtex-robust-decoder/R-n-D/zotero-better-bibtex" 312d0adfff74c11c06910572b2c55bb0be0d9772           
git_repo_checkout_branch "../bibtool"                             fdeda59cf95fc94cd0dcfd5f905412f41d93815a master    
git_repo_checkout_branch "../bibutils"                            f96b97934122ee0937708fe8d06b5ee09f78a244 master    
git_repo_checkout_branch "../bin2cpp"                             6fddc52006e3b009fe2e3a90f49c478cfaa4e3a4 master    
git_repo_checkout_branch "../binary_bakery"                       890c807e67ed5e6f8150e90a8920d7827e5ac0ce master    
git_repo_checkout_branch "../binary_bakery/thirdparty/doctest"    4d8716f1efc1d14aa736ef52ee727bd4204f4c40           
git_repo_checkout_branch "../binary_bakery/thirdparty/stb"        af1a5bc352164740c1cc1354942b1c6b72eacb8a           
git_repo_checkout_branch "../binary_search"                       a94f7e85906ff91156e89d32a36c17c7b4a914a1 master    
git_repo_checkout_branch "../binary2strings"                      02f0c983aeede7ed9acbee96a43f9142dc7ba404 main      
git_repo_checkout_branch "../binlog"                              125b7620efe72cab1ca183b27400a543d75c8252 main      
git_repo_checkout_branch "../Bi-Sent2Vec"                         b3bf758f86a7006112a7a65bf9955d88ef3465d7 master    
git_repo_checkout_branch "../BitFunnel"                           b8ec70eeb3aa2f6aef6166feb6780fac3acf981b master    
git_repo_checkout_branch "../bitrush-index"                       bfb23a73b872a9d537081e25d767f2e04bf00d9a master    
git_repo_checkout_branch "../bitsery"                             4fb6388c214e15cf5c6954294ae4dbaabf49c669 master    
git_repo_checkout_branch "../BLAKE3"                              0b5b6fab7acf49def02f533ff6573ff389205c2a master    
git_repo_checkout_branch "../blaze"                               eb8ef721f5024eb5bc75f9b08ffe63609515d26e master    
git_repo_checkout_branch "../blazingmq"                           1a6b88cefeb574370abc4bf1990a62f2b66c18bb main      
git_repo_checkout_branch "../BlingFire"                           3a8d44a168c0b8cf2ba1e1e8a5e25e4646a838e7 master    
git_repo_checkout_branch "../blis"                                6d0ab74f6975fdf4d19cee06d946b09b6ca89656 master    
git_repo_checkout_branch "../blitsort"                            0942ef920c5ae05cb415b93a88809b4c40ca9ad8 main      
git_repo_checkout_branch "../bloom"                               7309d713e0f02189e059a997bdb5e5dd3ea4a6a1 master    
git_repo_checkout_branch "../bolt"                                3f0c68a6fd01eef7be89696489c9301497e9c8cf master    
git_repo_checkout_branch "../boost"                               e11afb03241a3351633ffbaf2d529b0c5fbc5338 master    
git_repo_checkout_branch "../boost/libs/accumulators"             9d9e5dae2202660f57e2dc91efb620aa001525b3 master    
git_repo_checkout_branch "../boost/libs/algorithm"                32c5a6327cfdca5d41ce0f1d8849b811886daa2f master    
git_repo_checkout_branch "../boost/libs/align"                    5ad7df63cd792fbdb801d600b93cad1a432f0151 master    
git_repo_checkout_branch "../boost/libs/any"                      436e2991f9ad4bb9bbb70b01c688539382197c47 master    
git_repo_checkout_branch "../boost/libs/array"                    23f6b27c0d9916b9932baac898ae3009817a9153 master    
git_repo_checkout_branch "../boost/libs/asio"                     c28d453674dd2071fdc8cce5ffabcb54c910f466 master    
git_repo_checkout_branch "../boost/libs/assert"                   2242cfb58269c03328957860006076386e7fa356 master    
git_repo_checkout_branch "../boost/libs/assign"                   ababd47970e8a5fa1bebc8ccad526c4f25bd867a master    
git_repo_checkout_branch "../boost/libs/atomic"                   fbdb5f44d4ace030d8a8836cc4f3738bcc1c6d72 master    
git_repo_checkout_branch "../boost/libs/beast"                    fee9be0be10c9c9a22ac1505a710d1d8ed5a3dfb master    
git_repo_checkout_branch "../boost/libs/bimap"                    f57c83ab171e794ea003987aa60fccb533a734a2 master    
git_repo_checkout_branch "../boost/libs/bind"                     97776ec7ba6217ecdfb8fd777dec85117de6f188 master    
git_repo_checkout_branch "../boost/libs/callable_traits"          2a56a3a2496cdb66496f844db55085dd992d5e49 master    
git_repo_checkout_branch "../boost/libs/charconv"                 bde521e1c9db72f8898005f17950dad4dd830a90 master    
git_repo_checkout_branch "../boost/libs/chrono"                   ee0d6d543a37d9b7243682549e9ae359eb89daa9 master    
git_repo_checkout_branch "../boost/libs/circular_buffer"          a08a5b55ee82e0c2487523471379ac53a23935dc master    
git_repo_checkout_branch "../boost/libs/cobalt"                   af72ced0518b350044c35f8aca8232aa2c0e79c3 master    
git_repo_checkout_branch "../boost/libs/compat"                   4abae7082ae72dfa686f3f3228be670bc9dd4618 master    
git_repo_checkout_branch "../boost/libs/compatibility"            d0caac5c346f7e24b4f8ec1e55110119492b64bd master    
git_repo_checkout_branch "../boost/libs/compute"                  36350b7de849300bd3d72a05d8bf890ca405a014 master    
git_repo_checkout_branch "../boost/libs/concept_check"            37c9bddf0bdefaaae0ca5852c1a153d9fc43f278 master    
git_repo_checkout_branch "../boost/libs/config"                   6e5b06f941a18cc1dbec87c3359cedc67c4187fe master    
git_repo_checkout_branch "../boost/libs/container"                e08a064896048daa306b82d7525e5b524051fb42 master    
git_repo_checkout_branch "../boost/libs/container_hash"           3c9ce69f92d8eacba62d389636ed5da067b3cce5 master    
git_repo_checkout_branch "../boost/libs/context"                  f7c27e2293912466f2806cba5597a2e052242720 master    
git_repo_checkout_branch "../boost/libs/contract"                 eca93d24b5d3bb909ed64c12b5feb5296c5cc070 master    
git_repo_checkout_branch "../boost/libs/conversion"               8a860e05d0f90d539e3e8710f6924668f1292a76 master    
git_repo_checkout_branch "../boost/libs/convert"                  0dd7a76b1c051c048b4991b7aa9c8b5aeb5776ee master    
git_repo_checkout_branch "../boost/libs/core"                     622476533c60b979d0b6a406d601c88219092cdb master    
git_repo_checkout_branch "../boost/libs/coroutine"                1e1347c0b1910b9310ec1719edad8b0bf2fd03c8 master    
git_repo_checkout_branch "../boost/libs/coroutine2"               d7e1c1c4abcf8c1e90097279e485edea0b253a80 master    
git_repo_checkout_branch "../boost/libs/crc"                      13f9200ecacb011ba52bc3b0bea7955634de1499 master    
git_repo_checkout_branch "../boost/libs/date_time"                75be56b4c85d8e2dcbc22a1eb251d18cc942fceb master    
git_repo_checkout_branch "../boost/libs/describe"                 50719b212349f3d1268285c586331584d3dbfeb5 master    
git_repo_checkout_branch "../boost/libs/detail"                   a54b2619f8f75861836114d02a3fc70c7c9b3474 master    
git_repo_checkout_branch "../boost/libs/dll"                      477583869ec304899170728e32ce9f0c5c597af2 master    
git_repo_checkout_branch "../boost/libs/dynamic_bitset"           8e20aa1462bf6dcadc338835df529a6d568431b1 master    
git_repo_checkout_branch "../boost/libs/endian"                   ced7f38d24420723c1abe9d7b19f299b321c5bcf master    
git_repo_checkout_branch "../boost/libs/exception"                ece51fe0f7b8273ffc3fa626c3d1442f7af24ef9 master    
git_repo_checkout_branch "../boost/libs/fiber"                    88b8304e78dfab4baee5d6beca09938d2826061a master    
git_repo_checkout_branch "../boost/libs/filesystem"               a5baf7d1969f61dff90f39f68dfbca234d905af8 master    
git_repo_checkout_branch "../boost/libs/flyweight"                e9f3a0a005eca8baa377f13423107b35985d9119 master    
git_repo_checkout_branch "../boost/libs/foreach"                  cc2f75ae30492b9de69b3b692f5c59afcb7dea5e master    
git_repo_checkout_branch "../boost/libs/format"                   9c6964ae01169974da56ba0d3f32ff2627604776 master    
git_repo_checkout_branch "../boost/libs/function"                 1204b7d20091c1ac65fb02a1d5991a82098e4f77 master    
git_repo_checkout_branch "../boost/libs/function_types"           895335874d67987ada0d8bf6ca1725e70642ed49 master    
git_repo_checkout_branch "../boost/libs/functional"               6a573e4b8333ee63ee62ce95558c3667348db233 master    
git_repo_checkout_branch "../boost/libs/fusion"                   53da4e0b2c8cd4969b09fa646d314ac0c414c1ff master    
git_repo_checkout_branch "../boost/libs/geometry"                 f82eb32da79641697583a43be9988d7517d8553c master    
git_repo_checkout_branch "../boost/libs/gil"                      201f31c76eed54b304f8d89e44da08a5e8825094 master    
git_repo_checkout_branch "../boost/libs/graph"                    198616d896e0db612d507baed7f8e01c38809066 master    
git_repo_checkout_branch "../boost/libs/graph_parallel"           5520a5617d2763c48a06a4ff277ad76e665c7cf3 master    
git_repo_checkout_branch "../boost/libs/hana"                     275ee334d4c406643e9f560c40f9b73638cd9c7e master    
git_repo_checkout_branch "../boost/libs/headers"                  5c0228ed90ff32a54ba0b015ddae2b170062dcb1 master    
git_repo_checkout_branch "../boost/libs/heap"                     dc2f19f8815cbe0654df61bfc5f31ad8b06fc883 master    
git_repo_checkout_branch "../boost/libs/histogram"                a29729e6682652800b06dc8aded29bbeb4acea61 master    
git_repo_checkout_branch "../boost/libs/hof"                      63ac019fca325038bfb4f56db17fbb281d2b5f49 master    
git_repo_checkout_branch "../boost/libs/icl"                      2741c3a1b7b79f7326360c26c3e1588b385c9e53 master    
git_repo_checkout_branch "../boost/libs/integer"                  fbaf2dee580e378bc217a9efc86b6b9c25e3e560 master    
git_repo_checkout_branch "../boost/libs/interprocess"             9fc4ee7dd7277d86c691921007856aca99c3c1ac master    
git_repo_checkout_branch "../boost/libs/intrusive"                b9b83bd9e691cde4f116d8a0bd4e09b91e70ce4f master    
git_repo_checkout_branch "../boost/libs/io"                       342e4c6d10d586058818daa84201a2d301357a53 master    
git_repo_checkout_branch "../boost/libs/iostreams"                da7e81cf051499c55d915078687f8d6e858cd16c master    
git_repo_checkout_branch "../boost/libs/iterator"                 ce030ab2c314678b1bd7d20f92b155a4e17e719d master    
git_repo_checkout_branch "../boost/libs/json"                     324a7eb1478083f1c4c29ff460d4ac35d1878726 master    
git_repo_checkout_branch "../boost/libs/lambda"                   af16036c576b14896e8c62cf0bd0a1f8235ce07b master    
git_repo_checkout_branch "../boost/libs/lambda2"                  97f43720a1d088b6ccecbb6d55964bdecd031bd4 master    
git_repo_checkout_branch "../boost/libs/leaf"                     5991052a6bb59ebc39557b4fc1ac734af16c01b7 master    
git_repo_checkout_branch "../boost/libs/lexical_cast"             71a184d20fab0577b8bca7b9e9ffd6830cb56018 master    
git_repo_checkout_branch "../boost/libs/local_function"           258aeaa6c1a9618c02ca4e4af2890e70833035f0 master    
git_repo_checkout_branch "../boost/libs/locale"                   52cf8f8a5e23fc6ab5e3d5c8c5657f178ec35e90 master    
git_repo_checkout_branch "../boost/libs/lockfree"                 fdd4d0632dd0904f6e9c656c45397fe8ef985bc9 master    
git_repo_checkout_branch "../boost/libs/log"                      028247d2e6f4d55713d26c0250ce9b762148db2c master    
git_repo_checkout_branch "../boost/libs/logic"                    145778490c2d332c1411df6a5274a4b53ec3e091 master    
git_repo_checkout_branch "../boost/libs/math"                     4c2cdc2cf67060db2053a5db10da344cf7d42681 master    
git_repo_checkout_branch "../boost/libs/metaparse"                0ef448c1a7ce22b5de514f9cd504c323c28f4379 master    
git_repo_checkout_branch "../boost/libs/move"                     70c57e804f6c287c0ee3ab39c2ef1bb9ec9c02e5 master    
git_repo_checkout_branch "../boost/libs/mp11"                     a896dfc88dea2a336c6608d6f422f00b95ff71ee master    
git_repo_checkout_branch "../boost/libs/mpi"                      273afde6ac85ab8df4837e9a9a70316d47c8ee4e master    
git_repo_checkout_branch "../boost/libs/mpl"                      e9cbd523165856e6875122e91a761f1c5be25907 master    
git_repo_checkout_branch "../boost/libs/msm"                      f607d5154df4a5cc7f5ae014f0796f0b21b8bfc4 master    
git_repo_checkout_branch "../boost/libs/multi_array"              0c5348bef71b890c4bd06eff1ee5ebda69e7b27a master    
git_repo_checkout_branch "../boost/libs/multi_index"              d702a48363997f65fb717346f6694e0703902f8a master    
git_repo_checkout_branch "../boost/libs/multiprecision"           b484d2f158df88e04470e7da4bcc59bf63f65688 master    
git_repo_checkout_branch "../boost/libs/mysql"                    3a49afeb8770c55c506e5368f66d3bfc29eb8fd9 master    
git_repo_checkout_branch "../boost/libs/nowide"                   7ea5d333cce9f07d09dc59272771b610c6b33126 master    
git_repo_checkout_branch "../boost/libs/numeric/conversion"       50a1eae942effb0a9b90724323ef8f2a67e7984a master    
git_repo_checkout_branch "../boost/libs/numeric/interval"         2eda7413ac16dd4158005446438daf8a7e435dd9 master    
git_repo_checkout_branch "../boost/libs/numeric/odeint"           b21cbdcbe12d36431827acfeeee3a8d2cf3e16f5 master    
git_repo_checkout_branch "../boost/libs/numeric/ublas"            15d871b410ff92592c6f3e0a53550035e7817046 master    
git_repo_checkout_branch "../boost/libs/optional"                 c1519884edfca56db6364282aca745f647ffcb2b master    
git_repo_checkout_branch "../boost/libs/outcome"                  19a4baf51d41cc24987d5101aba41e404be5e70b master    
git_repo_checkout_branch "../boost/libs/parameter"                c142f7bdc27ed5abf945370c3bd82750fc0bdef1 master    
git_repo_checkout_branch "../boost/libs/parameter_python"         1f7f9ce9930119f0dda7dcd5e1ec3b5ed7c6b091 master    
git_repo_checkout_branch "../boost/libs/pfr"                      e1e908e804149e12fc2e442a95f5efaae0cd1aa6 master    
git_repo_checkout_branch "../boost/libs/phoenix"                  8913607a3788cb82d48ed461ea59c919b7bad3df master    
git_repo_checkout_branch "../boost/libs/poly_collection"          0b8bfc4cff012d0f23049fc5a0009ac4abadceb4 master    
git_repo_checkout_branch "../boost/libs/polygon"                  8ba35b57c1436c4b36f7544aadd78c2b24acc7db master    
git_repo_checkout_branch "../boost/libs/pool"                     ec7da07ed13e0c61e50d945b574a12ae7ec83cf4 master    
git_repo_checkout_branch "../boost/libs/predef"                   9aca7f5b609a731106a6d70e8dca9a4196dca968 master    
git_repo_checkout_branch "../boost/libs/preprocessor"             c4ea7e40d365ba28faecef8917d5c3f1e0121bf9 master    
git_repo_checkout_branch "../boost/libs/process"                  9561ebad1c1170ed7a489fc1ced8425f34ce84bc master    
git_repo_checkout_branch "../boost/libs/program_options"          06e103d363b1380ed6c95e9cb25ab4f0ac8120bc master    
git_repo_checkout_branch "../boost/libs/property_map"             e3a3c3655f4118fd15a02d8315f86a48db7390fd master    
git_repo_checkout_branch "../boost/libs/property_map_parallel"    a2f90e9660e4e7e012c0b54a1338d8e69fb71906 master    
git_repo_checkout_branch "../boost/libs/property_tree"            8080ecd14f2d952a4bb7ae869fc0f54f54f5a31f master    
git_repo_checkout_branch "../boost/libs/proto"                    7f924934689b940f3a72212ab0f714ec6fd6e34b master    
git_repo_checkout_branch "../boost/libs/ptr_container"            cf94735c87e073b33e54887a3d5e33598177ee1a master    
git_repo_checkout_branch "../boost/libs/python"                   47d5bc76f69e20625214381c930a2fad5765e2b3 master    
git_repo_checkout_branch "../boost/libs/qvm"                      69fad4886b0c806e7929fbec70031879e25a722c master    
git_repo_checkout_branch "../boost/libs/random"                   29ac88879985418c6284587485d0ad8c36e33cbc master    
git_repo_checkout_branch "../boost/libs/range"                    2bb6b636796f7b008196888613f51f5bb347c77d master    
git_repo_checkout_branch "../boost/libs/ratio"                    d5b33caa7d564be9be6d962b18659b7741d764ac master    
git_repo_checkout_branch "../boost/libs/rational"                 564623136417068916495e2b24737054d607347c master    
git_repo_checkout_branch "../boost/libs/redis"                    a4d2bb983dba0aac546a41d04f6af94568e817fc master    
git_repo_checkout_branch "../boost/libs/regex"                    4cbcd3078e6ae10d05124379623a1bf03fcb9350 master    
git_repo_checkout_branch "../boost/libs/safe_numerics"            777e0be5ec763d0333a717c5e421a4f7c5e5bdc9 master    
git_repo_checkout_branch "../boost/libs/scope"                    bc85d865f2300cc8b7211a90f9c1278ce66b2c52 master    
git_repo_checkout_branch "../boost/libs/scope_exit"               60baaae454b2da887a31cf939e22015b6263c9e4 master    
git_repo_checkout_branch "../boost/libs/serialization"            a20c4d97c37e5f437c8ba78f296830edb79cff9e master    
git_repo_checkout_branch "../boost/libs/signals2"                 2d199fc765b13140dea25edcde47f45a386c38b0 master    
git_repo_checkout_branch "../boost/libs/smart_ptr"                c8ef3e2276d3925288afc6d6e5ee841d0d7feb0e master    
git_repo_checkout_branch "../boost/libs/sort"                     d12ad000fc63d9c21e299c9ef420ccf85cba8548 master    
git_repo_checkout_branch "../boost/libs/spirit"                   43112c3f055fa109f20b8e8e6e50d0a016da742a master    
git_repo_checkout_branch "../boost/libs/stacktrace"               23e1213f54e2ef0bd89ac2beadc4ca5c1a510228 master    
git_repo_checkout_branch "../boost/libs/statechart"               586445b824c5cf0e7e6ce4ff2df620fda5d0f0d7 master    
git_repo_checkout_branch "../boost/libs/static_assert"            ba72d3340f3dc6e773868107f35902292f84b07e master    
git_repo_checkout_branch "../boost/libs/static_string"            bff5cb65a5cb9151aacaf56abe80125e0128f43a master    
git_repo_checkout_branch "../boost/libs/stl_interfaces"           0f422d58cb392674bace893d237a6ddd121d8c31 master    
git_repo_checkout_branch "../boost/libs/system"                   a664cd1de6261bbafee00d530f082c878eec73ff master    
git_repo_checkout_branch "../boost/libs/test"                     871031c68c520dcecca17c1463e58a36d5afe729 master    
git_repo_checkout_branch "../boost/libs/thread"                   aec18d337f41d8e3081ee65f5cf3b5090179ab0e master    
git_repo_checkout_branch "../boost/libs/throw_exception"          6ff2e5dca53fc50bef54ef3eeaaed83d35cbc061 master    
git_repo_checkout_branch "../boost/libs/timer"                    c9668fff563679acb0def47fe0f0a4cefe40fa99 master    
git_repo_checkout_branch "../boost/libs/tokenizer"                90106f155bd72b62aaca0d9ad826f4132030dba0 master    
git_repo_checkout_branch "../boost/libs/tti"                      a09ad0a24c982096c102847411c37045865a8098 master    
git_repo_checkout_branch "../boost/libs/tuple"                    b67941dd7d03536a854b96f001954792311ab515 master    
git_repo_checkout_branch "../boost/libs/type_erasure"             729f3e739abc65d36d46df470c5bab735599d042 master    
git_repo_checkout_branch "../boost/libs/type_index"               795773e0e0c5c16dfb9235c7374e4767c842de5d master    
git_repo_checkout_branch "../boost/libs/type_traits"              cc6fc3daa8e20c4a70b563d67ceb4c34d8c1c4d7 master    
git_repo_checkout_branch "../boost/libs/typeof"                   4bc9de322cd44373435540d4e6c8f207892fc9a0 master    
git_repo_checkout_branch "../boost/libs/units"                    45787015dd8c11653eb988260acf05c4af9d42e5 master    
git_repo_checkout_branch "../boost/libs/unordered"                d61719a196a6022d9dc68f5118c16c881bb5a0d4 master    
git_repo_checkout_branch "../boost/libs/url"                      c9a39b93eb05f1fed47361cff1572b4bea4b1f82 master    
git_repo_checkout_branch "../boost/libs/utility"                  94644596c2fd429c997f5db284d669bc910b571e master    
git_repo_checkout_branch "../boost/libs/uuid"                     02c82cea9c82e4fdbc32b58e5a2e9f97dfc50755 master    
git_repo_checkout_branch "../boost/libs/variant"                  0fd179fbd83bf600e84a2f8da422b84263cdc922 master    
git_repo_checkout_branch "../boost/libs/variant2"                 f5cd36af3d47203038a6700f1163a554016ee0dc master    
git_repo_checkout_branch "../boost/libs/vmd"                      34cad2c1a574d445812c7c2432d3a5a5c843b412 master    
git_repo_checkout_branch "../boost/libs/wave"                     13a8e179ce8c7ad7e657ef79ffcf0566a0f510de master    
git_repo_checkout_branch "../boost/libs/winapi"                   ea553ab4d2e4cba1448d23a542993692c9d385f7 master    
git_repo_checkout_branch "../boost/libs/xpressive"                4679fbd23f962bfa78d44acf5fa48f6f790642c0 master    
git_repo_checkout_branch "../boost/libs/yap"                      ae49bf2744586e6bd6c0cedff4500a58a4386860 master    
git_repo_checkout_branch "../boost/more"                          2dd8700f471fae5321a9cd523a377a07bcb21a15 master    
git_repo_checkout_branch "../boost/tools/auto_index"              91e2f15b8b1e7d609b8398286833cb9847984ecc master    
git_repo_checkout_branch "../boost/tools/bcp"                     2bb48d28b1fb96320f2d72a9299f1e5e4d41d31d master    
git_repo_checkout_branch "../boost/tools/boost_install"           2132658243024b77693492a7b61822079c206a2e master    
git_repo_checkout_branch "../boost/tools/boostbook"               5efbdc20b8c943195a2fffa25f4fb843d23f28bb master    
git_repo_checkout_branch "../boost/tools/boostdep"                8f9cb2ef559fbe760f6522ddb8f693c02b83c032 master    
git_repo_checkout_branch "../boost/tools/build"                   4a52d8c06635435b64e31a56eaf7ca5dc912a71d master    
git_repo_checkout_branch "../boost/tools/check_build"             092f1f300410bee1495c0b8f27d61ac32bc16c42 master    
git_repo_checkout_branch "../boost/tools/cmake"                   bb741d09d2cb12f3934896880c6ecaf6de4ba707 master    
git_repo_checkout_branch "../boost/tools/docca"                   859ed19ae6a7b1f0147cc49c99a838298ddd0369 master    
git_repo_checkout_branch "../boost/tools/inspect"                 d18744cddbd4304f7b939131004571dbb301fa4f master    
git_repo_checkout_branch "../boost/tools/litre"                   564d4d8d30b7e03ac5e25d78e14d2c19fa321c83 master    
git_repo_checkout_branch "../boost/tools/quickbook"               56e4aca294d94d5fbcc19d44ea3762b9ec5e5ac9 master    
git_repo_checkout_branch "../boost-url"                           18033bed8faafcf659502393b02b2d1801e91813 develop   
git_repo_checkout_branch "../boringssl"                           ba62c812f01fb379f49f94a08a2d1282ce46e678 master    
git_repo_checkout_branch "../BoxFort"                             1018a44e63b57e9ffc3b8b68b6c8a8aa8f342d2a master    
git_repo_checkout_branch "../bplustree"                           44afb110e00dc923caf079eb9c81fd3b03db7ab5 disk-io   
git_repo_checkout_branch "../breakpad"                            b9b59d33d485281182a32390287bdde9bcad47dc main      
git_repo_checkout_branch "../brotli"                              f86529623dbd4db02e76ea1ca9da821ec934bf77 master    
git_repo_checkout_branch "../brown-cluster"                       fe90f87f9cd10d76c834166b4a8560eae3bc38c9 master    
git_repo_checkout_branch "../brunsli"                             cbbc39ada0600725a82f25f142352143ebb2763d master    
git_repo_checkout_branch "../bustache"                            1a6d4422bff46c7c8f37d2ba48c910532bdc8b37 master    
git_repo_checkout_branch "../butteraugli"                         70473ddc3cdbd724130402eece9dd352e2a998f4 master    
git_repo_checkout_branch "../bxzstr"                              6c426ef2107f812f34ba7550d448c1062a6bd61d master    
git_repo_checkout_branch "../bzip2"                               0b9e17fc184db599871772cf0f471f65a9e8053c master    
git_repo_checkout_branch "../bzip3"                               ad30f13188e6090720f5aa734609e31ea0a9b6f3 master    
git_repo_checkout_branch "../CacheLib"                            da5708a2941724150b22474ef6ecdd44623de8e5 main      
git_repo_checkout_branch "../CacheLib/cachelib/external/fbthrift" f6681150810835c02e9c1efd1ec8f5d615c51618           
git_repo_checkout_branch "../CacheLib/cachelib/external/fizz"     f1ff66035720aee4983b330201956abf0dbb9dfa           
git_repo_checkout_branch "../CacheLib/cachelib/external/folly"    f601d244aac60d591228cfd41a566d0039d4deef           
git_repo_checkout_branch "../CacheLib/cachelib/external/mvfst"    ce9687220e47b01232d2186b610b23958009792a           
git_repo_checkout_branch "../CacheLib/cachelib/external/wangle"   0f6bdb225f0eb2a363d9171425966977c2b035d8           
git_repo_checkout_branch "../cachelot"                            68520452f6403d928f20f23b2c93dc2f5c346edc master    
git_repo_checkout_branch "../caches"                              3fc9e07d49ac46272a583de0555a9cf376cdf316 master    
git_repo_checkout_branch "../caffe"                               9b891540183ddc834a02b2bd81b31afae71b2153 master    
git_repo_checkout_branch "../cairo"                               dc0ff5890dade415fd1ab723d5f310e7f611b38f master    
git_repo_checkout_branch "../cairo-demos"                         ec821ac1a0c47082c58bd7f5fae4da5afa27c496 master    
git_repo_checkout_branch "../calibre"                             78e85f402f565934030a029a08f0d0199d3ffc90 master    
git_repo_checkout_branch "../capnproto"                           d9b586c7da4912214f96c680ffc51396b4a50052 v2        
git_repo_checkout_branch "../Capture2Text"                        adcce2467568c230411851a1cef1d3bad44a4115 master    
git_repo_checkout_branch "../capture-thread"                      a780de1c20e2442139b3f06fede68d41161849be current   
git_repo_checkout_branch "../catboost"                            037807982839cef41957e09b3a40401af3dd2672 master    
git_repo_checkout_branch "../c-blosc2"                            cf04e7e10ce620c638e661fddd6d5b87dfce6d76 master    
git_repo_checkout_branch "../cctz"                                5b5c77df48fdffb60e492a159d03a05203d820e2 master    
git_repo_checkout_branch "../ccv-nnc"                             11365b1774e8241a0892bbe4817e24ba2a8e7a0c unstable  
git_repo_checkout_branch "../cdc-file-transfer"                   370023a944d8c81f60463b6659d0de4de99637a7 main      
git_repo_checkout_branch "../cef-pdf"                             0089a136dbff83c05751cbbba48a455d12476fe1 master    
git_repo_checkout_branch "../cel-cpp"                             783d4803c91129de3545b0450aa09ed0b6138c04 master    
git_repo_checkout_branch "../cel-spec"                            3cdaf9bc892fd2d695860b557c798ef8335e3f68 master    
git_repo_checkout_branch "../cereal"                              a79b0bb4f5ca0e27fb7275ff873b49c67ad642c3 master    
git_repo_checkout_branch "../ceres-solver"                        ee6cebe49abe3be8628a81e39bcea8cb7b96a088 master    
git_repo_checkout_branch "../cfgpath"                             7305cf5039a430bb9c83bbbe2f44552899980fcb master    
git_repo_checkout_branch "../chewing_text_cud"                    245c14b5eb980716e78acba05c2d6cc14192267c main      
git_repo_checkout_branch "../chibi-scheme"                        86ef8f5f1d9893e32188ad5bc1666e7538bf7d83 master    
git_repo_checkout_branch "../CHM-lib"                             e5cc1ca9e9b29afe2ebc75e38ce6aaae986c3658 master    
git_repo_checkout_branch "../chromium-snss-parse"                 f0a1daa499f66b892ac8bb7b5b1e7540fe3a4274 master    
git_repo_checkout_branch "../cilantro"                            57ad1a397b73b6f4bbf9604fd75f8fe4363206a7 master    
git_repo_checkout_branch "../CImg"                                2baf573f649c773c8889c7f624306cdd610f1076 master    
git_repo_checkout_branch "../citation-abbreviations"              77afacdd635d0f34dbb303a493cbc1188d68262d master    
git_repo_checkout_branch "../citation-journals"                   768f9af08861b9b117cb7f0c4dbf319b2f38a306 master    
git_repo_checkout_branch "../citation-styles"                     14bad924acba49aae634d40b571b52a0b29f47c5 master    
git_repo_checkout_branch "../citeproc-js"                         59fbf78c05f1edf9aaaf58ca4c51102141384992 master    
git_repo_checkout_branch "../civetweb"                            e6b8c1b984bd8b32a55d7d35ab29f77ef02a9a01 master    
git_repo_checkout_branch "../cjose"                               9261231f08d2a3cbcf5d73c5f9e754a2f1c379ac master    
git_repo_checkout_branch "../cJSON"                               424ce4ce9668f288fb4ab665775546d3ed709e96 master    
git_repo_checkout_branch "../clBLAS"                              02fb83cf7d7a7a146307542014d5b8505ab38ae2 master    
git_repo_checkout_branch "../CLBlast"                             3d99d8851e3414b4a690c65eb6915917255abd54 master    
git_repo_checkout_branch "../CLBlast-database"                    717cf4d212113b5209bcd844219bf14b069faf88 master    
git_repo_checkout_branch "../cld1-language-detect"                570789a49822a242cb60553c3d07be4739e238d0 master    
git_repo_checkout_branch "../cld2-language-detect"                b56fa78a2fe44ac2851bae5bf4f4693a0644da7b master    
git_repo_checkout_branch "../cld3-language-detect"                b48dc46512566f5a2d41118c8c1116c4f96dc661 master    
git_repo_checkout_branch "../cli11"                               f68083a948bfc26ba17a1dcf1a7bbae99ef4052c master    
git_repo_checkout_branch "../clipp"                               99488f571a8b5ce63b611d8b81f9d7b55157c1d3 master    
git_repo_checkout_branch "../Clipper2"                            ff378668baae3570e9d8070aa9eb339bdd5a6aba main      
git_repo_checkout_branch "../clp"                                 64e59414e43d237d0082a2c12df338e041522d7b main      
git_repo_checkout_branch "../CLTune"                              6a13b43af09bbbfd3b83223c5a1c9c57d63c0330 master    
git_repo_checkout_branch "../Cmathtuts"                           a3610505e04c162c48ad8b8eab9745b32f2f0b6d master    
git_repo_checkout_branch "../cmocka"                              2cdeeae61873f4c19debeca3e8b5ac0927e63602 master    
git_repo_checkout_branch "../cmph-hasher"                         464c540e0d37d60c120000c3a489f55c6b086dfa master    
git_repo_checkout_branch "../CNTK"                                10a8ffcf50d7b9225f3236ffcfdc422b2014fb92 master    
git_repo_checkout_branch "../colm"                                28b6e0a01157049b4cb279b0ef25ea9dcf3b46ed master    
git_repo_checkout_branch "../colorm"                              4d41b6e0fbc32b3237e7e7171850e5f461368050 master    
git_repo_checkout_branch "../ColorMagic"                          a4182c63325b27e8d21e39acb7db1f3c68b89628 develop   
git_repo_checkout_branch "../colormap-shaders"                    28864f924f9eb20d4911cc32bc504c51905054c3 master    
git_repo_checkout_branch "../ColorPaletteCodable"                 18d0efe7d9bfe692dbd48171ca4e15d5f783fbfa main      
git_repo_checkout_branch "../ColorSpace"                          2b28f91cc92d07265190c64522b4d7c5e07d09b2 master    
git_repo_checkout_branch "../color-util"                          8db4b1dc29f9847063852711f39b523aaa37d3af master    
git_repo_checkout_branch "../comdb2-bdb"                          fca099ba93448a93792b48cdc07d5193e60a3aa2 master    
git_repo_checkout_branch "../compact_enc_det"                     d127078cedef9c6642cbe592dacdd2292b50bb19 master    
git_repo_checkout_branch "../completesearch"                      e3f3e7c4e9832254db203e345f4b9b467a3e0ac0 master    
git_repo_checkout_branch "../concat"                              6aa47c009050dbab4c1a02bd77f9e224eb279701 master    
git_repo_checkout_branch "../concurrencpp"                        0c42a5d0053b1d1c0aead85af5d3d27656cff000 master    
git_repo_checkout_branch "../concurrentqueue"                     3d66f5e35b5d8ba0864b2ab14b1a836a35fb864c master    
git_repo_checkout_branch "../config-cpp"                          8dd083681fa9a71c7cfe8d6658452517280733b5 master    
git_repo_checkout_branch "../continuable"                         23a724cf5c3026155550dc802d283d713fdfd97e master    
git_repo_checkout_branch "../coost"                               864d39f586b1e010a02aa30e7427472933adeea1 master    
git_repo_checkout_branch "../cpp_rest_sdk"                        f776d3d9e2a7cdb946b0b6c58a5165b0453f0fa1 master    
git_repo_checkout_branch "../cpp-base64"                          951de609dbe27ce8864dfe47323c4ade96bee86e master    
git_repo_checkout_branch "../cpp-btree"                           c876a70384340b222c206f86ec1497bd05c5a72c master    
git_repo_checkout_branch "../cppdap"                              0f943b33579585492732533867da334fd3a1683a main      
git_repo_checkout_branch "../cppflow"                             99e04d7045af79ef8fe9f906cf0d9bd5559dd935 master    
git_repo_checkout_branch "../cpp-httplib"                         05f9f83240a388239c088f067a1e3e6af2a7bf51 master    
git_repo_checkout_branch "../cpp-ipc"                             035d76d5aaaa420a61d5e08be841cc20e585adde master    
git_repo_checkout_branch "../cppjieba"                            faa3476be1e11ccbf83a99aeb73161175e944cd2 master    
git_repo_checkout_branch "../cpplocate"                           ff2e12e88dce2847e0ffe0db8bccf095d71b474b master    
git_repo_checkout_branch "../cpp-netlib"                          552ce94bd91c055f11ba524adf0ca0712063d711 main      
git_repo_checkout_branch "../CppNumericalSolvers"                 450e62ba777e9581092e0dd45949e1dbfbb19ddf v2        
git_repo_checkout_branch "../cppsimhash"                          a88f1b5efd40b06fff39a523c209847b459f66a9 master    
git_repo_checkout_branch "../cpp-terminal"                        64dea63c40fbb64d943418bf1086ecb3053d4cc4 master    
git_repo_checkout_branch "../cpptoml"                             4620b27cc79156c748ca7f8b5fb64781ba85bd1c master    
git_repo_checkout_branch "../cppzmq"                              4ee4f7186957679ddb0775375ca9ef3b0a480942 master    
git_repo_checkout_branch "../cpu_features"                        049ce4e75268b3cbb03ab527ff0a82c598258234 master    
git_repo_checkout_branch "../cpuinfo"                             6be789e1f7d2f25c048ca6f83426f25b53217814 master    
git_repo_checkout_branch "../cpython"                             7852c3e21db5aa7bfbea80f33492b8e8f641e850 master    
git_repo_checkout_branch "../cqf"                                 b115e13cf0460b226647db621295e4682eb2a16d master    
git_repo_checkout_branch "../cr"                                  13fd7157fa2cef10967e027446a77247016c317e master    
git_repo_checkout_branch "../crc32c"                              9277a354e00c34f566e375f0b54823e918d40ce2 main      
git_repo_checkout_branch "../createprocess-windows"               eb8c56e5a7c72ed5a2d4be13a76e0440a028e45c master    
git_repo_checkout_branch "../CRFpp"                               1dc92a606f874a4fe52603803364cc1d90f952fb master    
git_repo_checkout_branch "../crfsuite"                            85fb9c737cad774d741bc36004b89270640d2e3f master    
git_repo_checkout_branch "../CRFsuite-extended"                   073d650b12460c1d6f1c3bf862e13dccaf473fc6 master    
git_repo_checkout_branch "../Criterion"                           206e18f306d77afaa65715e3b40ae6836bdefcd1 bleeding  
git_repo_checkout_branch "../CRoaring"                            abe92c57938ee0c4e344979793b78a7142d25f63 master    
git_repo_checkout_branch "../crow"                                4f89649dd63433ee10b5d41a277764686793cdd9 master    
git_repo_checkout_branch "../crumsort"                            e5a5be757cec2088a6559a6fd460eea0d7d0c578 main      
git_repo_checkout_branch "../cryptopp"                            6a7a11d999fa7c599a076913408d4518ea1c7628 master    
git_repo_checkout_branch "../CryptSync"                           1d6e4810a801d0bd527f5536aa9b0a8af1c1f267 main      
git_repo_checkout_branch "../csv-parser"                          31e22c2c51e8a22a5ae9cc66a192162552f204ee master    
git_repo_checkout_branch "../csvquote"                            3e26cee6ec9d05bec3e70506154fa01721888d06 master    
git_repo_checkout_branch "../csync2"                              83b36449abb4c2903ef3b40b46018240633989e0 master    
git_repo_checkout_branch "../CTCWordBeamSearch"                   bb9cfa4f1493ec6f810a37e5baa78cfdf99bf46a master    
git_repo_checkout_branch "../CTPL-Thread-Pool"                    437e135dbd94eb65b45533d9ce8ee28b5bd37b6d master    
git_repo_checkout_branch "../ctsa"                                2125b434630170152fc86dbc60e06d659778b93d master    
git_repo_checkout_branch "../cuckoofilter"                        cee8ec784336b4278086b361894ea3ff286d8388 master    
git_repo_checkout_branch "../cuckoo-index"                        cae12a1260352c7937855381295335927fb9a846 master    
git_repo_checkout_branch "../curl-impersonate"                    8249a451539b66cf244d791c27200862869fbafc main      
git_repo_checkout_branch "../curl-www"                            eca1b02227a8b06c28664cc8a87c2406255145e7 master    
git_repo_checkout_branch "../CurvatureFilter"                     b6697891fa853b0c2a35482e507cb7af708ce344 master    
git_repo_checkout_branch "../cvmatio"                             af8a9a112f75da11f942237b5baa2a229b0abc27 master    
git_repo_checkout_branch "../cv-VanishingPoint"                   860043738d1948dba6761f22f97a205798b1cd30 master    
git_repo_checkout_branch "../CxImage"                             e24dc719a471f9fc6b389b84641ea065e71c9e59 master    
git_repo_checkout_branch "../cxxopts"                             59656709c0c58fcd0ed18b38e02938dbe05284c5 master    
git_repo_checkout_branch "../cxxtest"                             a19f85fdf90f97e16d6e3e7e3d2d68c31cd89e3c master    
git_repo_checkout_branch "../cxxtest_catch_2_gtest"               694b12c5974859449e2f608e92c5e726f610f573 main      
git_repo_checkout_branch "../cxxtest_catch_2_gtest/3rd/Catch1"    ce556fd646d7ae909c174944ba8b73c7c4504e0b           
git_repo_checkout_branch "../cxxtest_catch_2_gtest/3rd/Catch2"    ce556fd646d7ae909c174944ba8b73c7c4504e0b           
git_repo_checkout_branch "../cxxtest_catch_2_gtest/3rd/check"     455005dc29dc6727de7ee36fee4b49a13b39f73f master    
git_repo_checkout_branch "../cxxtest_catch_2_gtest/3rd/cppcheck"  0fa066f27c52dda56994c30180d747d13b6bfd5c           
git_repo_checkout_branch "../cxxtest_catch_2_gtest/3rd/CppUTest"  a74cf2cc176fd34e67e0aee814db3ced74f2322a           
git_repo_checkout_branch "../cxxtest_catch_2_gtest/3rd/doctest"   2e2cb056bf5eb3f737182b3935275a5368da174e           
git_repo_checkout_branch "../Cysboard"                            387d15e72c87ac90c4760322b5db5065454ba630 master    
git_repo_checkout_branch "../darknet"                             f6afaabcdf85f77e7aff2ec55c020c0e297c77f9 master    
git_repo_checkout_branch "../dashing"                             0635bea4c779ff1628da3caf0a7d5fc0ce534967 main      
git_repo_checkout_branch "../datamash"                            56e2e5893df125d953765adc2851e8b0902ebf37 master    
git_repo_checkout_branch "../date"                                b51782ff011eb8213e14ebcc3f99ffffbb8302df master    
git_repo_checkout_branch "../datetimepp"                          fc174e672cbdcfdaf15cbdadd840e4c326932763 master    
git_repo_checkout_branch "../dateutils"                           fb2930c21a2aa5caeda4b1c3f5640a4a11915415 master    
git_repo_checkout_branch "../DBoW2"                               3924753db6145f12618e7de09b7e6b258db93c6e master    
git_repo_checkout_branch "../DBow3"                               f142cce260234dfec308ccb3332390fa0230263a master    
git_repo_checkout_branch "../dbscan"                              7059c43760f5640e7856f5cda32bd9c4000459f6 master    
git_repo_checkout_branch "../DCF-cuckoo-index"                    f943929afe9d8f973e9f847995d9c2c2095c566c master    
git_repo_checkout_branch "../debugbreak"                          df620f2cba4290ff8d2485eca661a1581553033b master    
git_repo_checkout_branch "../decision-tree"                       2f6a81421dcb17df56eb7d10794149d6366090e4 main      
git_repo_checkout_branch "../deepdetect"                          ac09c52af467a2863119b555f8a40dd244f65a6e master    
git_repo_checkout_branch "../delegate"                            64185e2d87d777ba84caad687f19a03f6745b42f master    
git_repo_checkout_branch "../dense_hash_map"                      74277fc4813028ae4a9e8d9176788eb8001177a6 master    
git_repo_checkout_branch "../density"                             67bebb7dd8d15d2b7a69776e8e739022cd8e29b9 master    
git_repo_checkout_branch "../densityxx"                           22b2a0e7a8d3f7343352a7d402823cbb3476f44a master    
git_repo_checkout_branch "../design-patterns-cpp"                 4fae40666a970dc4c7901df54964d6ebcd80ba5c master    
git_repo_checkout_branch "../detect-character-encoding"           d013143e480ea00bab98e959aff2d5b8b4da439b develop   
git_repo_checkout_branch "../DGM-CRF"                             33a2e9bdaf446378ec63c10b3a07b257e32aa1ef master    
git_repo_checkout_branch "../diffutils"                           5dee3199de571499a768f64cba2a179612110c2a master    
git_repo_checkout_branch "../Digital-Halftoning"                  6da1ae6e26ce1acf9536a47652de5f4ec08c6657 master    
git_repo_checkout_branch "../directorywatcher"                    9a35a2ba3122157f86ab7aa084e8128cfc2148e3 master    
git_repo_checkout_branch "../dirent"                              6d727ef57744d411d9aa21e196b6ecf5abe3dfa6 master    
git_repo_checkout_branch "../DiskANN"                             8aedb3a3d408b0ebde34f31eb4291bc8e0580122 main      
git_repo_checkout_branch "../djvulibre"                           c724cc0f6de7e3a4d8cb6904a92f8f57a216316e master    
git_repo_checkout_branch "../dkm"                                 9ffe86986fca0e3040719e9485c8c87d638fe4af master    
git_repo_checkout_branch "../dlfcn-win32"                         327bad09b6a19afb80957fed7268a3af4e0ddb97 master    
git_repo_checkout_branch "../dlib"                                aa136626631709f7aa181b2dbff1959eaa968e46 master    
git_repo_checkout_branch "../DocLayNet"                           66947398f04d050fed84e89e5509828f2ee17ecf main      
git_repo_checkout_branch "../doctest"                             1a042a43acbd2025a1e8c9ff7264d5b6b0276061 master    
git_repo_checkout_branch "../docxBox"                             7c7bf21edd9423f7c1519de848ebc9f018b34394 master    
git_repo_checkout_branch "../doh"                                 8654bc94ddbfaeec33e3403c6424e2dec8e86c30 master    
git_repo_checkout_branch "../doxa"                                033c08ea598cacd6094df34acde0e1742bfed2fc master    
git_repo_checkout_branch "../doxygen-awesome-css"                 40e9b25b6174dd3b472d8868f63323a870dfeeb8 main      
git_repo_checkout_branch "../DP_means"                            2d23e53d3a30eef76c835f15cff7241e51dd5114 master    
git_repo_checkout_branch "../dr_libs"                             da35f9d6c7374a95353fd1df1d394d44ab66cf01 master    
git_repo_checkout_branch "../dtl-diff-template-library"           c1166662f4020208819f345d3ad77965d34bb927 master    
git_repo_checkout_branch "../dtoa-benchmark"                      bf1fb58ade01658c908a498679e47f0b4e89aff7 master    
git_repo_checkout_branch "../duckdb"                              f81568998fd9a9ef25e9dbaf9ebbd6e9103f7ebb main      
git_repo_checkout_branch "../duktape"                             50af773b1b32067170786c2b7c661705ec7425d4 master    
git_repo_checkout_branch "../dynet"                               ee1cde7177635cb836070198f212622b2073a61c master    
git_repo_checkout_branch "../EASTL"                               7fadbf0da01e6f6e0e7038b1b34343a069b8fc51 master    
git_repo_checkout_branch "../easyexif"                            cd994a3b6009bc3c1f84062e96bd7f5ad16e85f6 master    
git_repo_checkout_branch "../easyloggingpp"                       607bb08b4d09efb810f9c57bbe4c34f1355edb20 master    
git_repo_checkout_branch "../easylzma"                            5f4e8fd29e54c42fd7dd6b754089bdfb85d5016e master    
git_repo_checkout_branch "../EasyOCR"                             c999505ef6b43be1c4ee36aa04ad979175178352 master    
git_repo_checkout_branch "../EasyOCR-cpp"                         cf08e1c9764b63c50e0fc63437639c7f21b21a33 main      
git_repo_checkout_branch "../ecal"                                f6737fb4252b9899e59a823c825548f37b844414 master    
git_repo_checkout_branch "../ECMA262"                             705742e103127e1be093c8cb10006974678a78db master    
git_repo_checkout_branch "../edit-distance"                       b3c46ddd3260b31d22fdf6671425a9deb671f728 master    
git_repo_checkout_branch "../efftw"                               499532ff131151020f47b20ffa95e0d0854b5121 main      
git_repo_checkout_branch "../efsw"                                8312a8de668d16d9630ca62f7f9b2bb08d301d21 master    
git_repo_checkout_branch "../EigenRand"                           8bc3c934af222ac8ee7baf059815d48ced550b62 main      
git_repo_checkout_branch "../emhash"                              d78a41ee5bad190867489c8c20bf745c4c02cc5b master    
git_repo_checkout_branch "../emphf-hash"                          87c36295e1d7a9d7167a7728406d302b1b089308 master    
git_repo_checkout_branch "../enca"                                27e901af4a96ebc9dd2f9dbdc6df502e8db2079d master    
git_repo_checkout_branch "../enkiTS-TaskScheduler"                52970bd9fba2d8ccc65f68e08a8a798e2dfc5de8 master    
git_repo_checkout_branch "../ensmallen"                           bfa048bf9ba167b04e9d035ce26160f04e13d67e master    
git_repo_checkout_branch "../epeg"                                17bbae0f0a0b777e5fb01e0d16891e07153a41eb master    
git_repo_checkout_branch "../EtwExplorer"                         601ae6a8f10bd841e8f93e943084f08d473fa8bb master    
git_repo_checkout_branch "../eventpp"                             d1f29076a1637eab8e4d3124db0584ba1bdd5261 master    
git_repo_checkout_branch "../everything-curl"                     28cae52bce9f4fc788cac6c8581a9a31e42e864e master    
git_repo_checkout_branch "../EWAHBoolArray"                       7254cffc5c35ce03225d78e041289fd5b946cd38 master    
git_repo_checkout_branch "../exif"                                0059882b24549705bcf242e20be4fbb202068ce3 master    
git_repo_checkout_branch "../exiv2"                               7a428276e3874d043489dcb8ff7cb0e904231f12 main      
git_repo_checkout_branch "../ex-leptonica-freetype-harfbuzz"      affc7ad6862fe477cc40d40984dcf22db4a55d33 master    
git_repo_checkout_branch "../expected"                            0476a3c733613e7d8af2f0ca52a6a2f96829f2d3 master    
git_repo_checkout_branch "../expected-lite"                       3634b0a6d8dffcffad4d1355253d79290c0c754c master    
git_repo_checkout_branch "../exprtk"                              07bb95d3ef1f17458be7e3558975b917347ddc90 master    
git_repo_checkout_branch "../Extensible-Storage-Engine"           24dc5ce9d9e80e7c9bf4db3cf1306b8dcec92a84 main      
git_repo_checkout_branch "../eytzinger"                           b615cb31626c2d7b1a0f1a7fa4a27f393d15cdff master    
git_repo_checkout_branch "../faiss"                               5e452ed52a976226e33eb9c90c34b3ede0193f3a main      
git_repo_checkout_branch "../falconn"                             e54012437590d74bea2c5af2e7f0c30f5a31d53f master    
git_repo_checkout_branch "../farmhash"                            0d859a811870d10f53a594927d0d0b97573ad06d master    
git_repo_checkout_branch "../farver-OKlab"                        aa5b136e8cdf798b85da7762a9119c2fafcdf91a main      
git_repo_checkout_branch "../fast_double_parser"                  694626652eff5b6847c0596c0d72ffb88272ed51 master    
git_repo_checkout_branch "../fast_float"                          1c1763339fed91b3aa1049bac694de057b565972 main      
git_repo_checkout_branch "../fast_pfor"                           88cc48d385f37f73007ad5b62fae49731fcd6db0 master    
git_repo_checkout_branch "../fastapprox"                          17d023550b4bc5301d1fe5a324555a04ba60e22a master    
git_repo_checkout_branch "../fastBPE"                             b60e0dac406510e3cd37de5e5a5895c67d0a9d0c master    
git_repo_checkout_branch "../fast-cpp-csv-parser"                 758f5665705a38da55322511d5b22fe2679918fe master    
git_repo_checkout_branch "../fastfilter_cpp"                      baba12f76abe3a618e49a743c64dc2a33ac79f26 master    
git_repo_checkout_branch "../FastGlobbing"                        7613858a6db946ab35067a18e02d8af279b2c72c main      
git_repo_checkout_branch "../fastgron"                            5d5998f18950c07402f679a19fe86cb2b9b2666c main      
git_repo_checkout_branch "../fasthashing"                         cbf35b710a3d2f17306f413546e1cf9702e8d817 master    
git_repo_checkout_branch "../fast-hex"                            a3487bca95127634a61bfeae8f8bfc8f0e5baa3f master    
git_repo_checkout_branch "../fast-kmeans"                         01551cd296e76bc2d7859b11f6de6a487ac247c0 master    
git_repo_checkout_branch "../fast-lzma2"                          ec7912a953e02f9562eebea0c44d5b362419486d master    
git_repo_checkout_branch "../fastops"                             7049667e85d3aa7301f450aae00a014e7cedd5f1 master    
git_repo_checkout_branch "../fastPRNG"                            5ce17711a65965b3726b3f0c62c7dcbd967a7b0f master    
git_repo_checkout_branch "../fastrange"                           5c984494b2e3fb862266d21e88db77f31f639f11 master    
git_repo_checkout_branch "../FastString"                          267e0e690cff0563492338e4199e22908e243a0f master    
git_repo_checkout_branch "../fastText"                            315874c70feca151b8a8ed42d496ba3a915c16f0 fastText  
git_repo_checkout_branch "../fatal"                               646e62f1eb512330b988635fdddacacf66eb14f8 main      
git_repo_checkout_branch "../faup"                                3a26d0a0d643f5035e1d846e6df9472569a6ef0e master    
git_repo_checkout_branch "../fbow"                                e148dbcbd8ee1976b1b07988b5761a9171b9f01a master    
git_repo_checkout_branch "../fCWT"                                7693c3ba517cba040e9a5d7531cde9d958ca19d3 main      
git_repo_checkout_branch "../ffht"                                fba727a3ff72c862260460631ae1cc8e3e44e861 master    
git_repo_checkout_branch "../FFME"                                473d351466e066c7d9d6f65027d747ee2642e0c6 master    
git_repo_checkout_branch "../FFmpeg"                              127ded507828a1127b0196ffde115171ab5c46f3 master    
git_repo_checkout_branch "../ffts"                                b22d839b61c5bd8a993e24ae3e01f39d9b5084fb master    
git_repo_checkout_branch "../fftw3"                               cab901fe465324cb46bd4953e18ddc610ade29b9 master    
git_repo_checkout_branch "../FiberTaskingLib"                     3a0566cf5e48f29e6fec5355bcd570baa30c9183 master    
git_repo_checkout_branch "../fifo_map"                            d732aaf9a315415ae8fd7eb11e3a4c1f80e42a48 master    
git_repo_checkout_branch "../figcone"                             d594d4f1f2d4bfb12dd512117d71e86c9d868eee master    
git_repo_checkout_branch "../figcone_ini"                         16677cc110c04bade3d2dda43a62fed7def3765c master    
git_repo_checkout_branch "../figcone_json"                        1e8979203d4dbbf054eb48bf9172af75426fc85b master    
git_repo_checkout_branch "../figcone_shoal"                       ae0305956baa41ca895c0634d5139f699cf897cd master    
git_repo_checkout_branch "../figcone_toml"                        54800d5ece09fdbea0990e240eb82888a989c69d master    
git_repo_checkout_branch "../figcone_tree"                        faf7a38a78b4055660bfffaf0143607c6fc39779 master    
git_repo_checkout_branch "../figcone_xml"                         04c846c78845f701f06b1427be455744d3a6cd0c master    
git_repo_checkout_branch "../figcone_yaml"                        9cb0b8604c904e9a43eddea625221887a9f0bdba master    
git_repo_checkout_branch "../figtree"                             ee925800bb25def579ad1a538881613937778c09 master    
git_repo_checkout_branch "../file"                                d6c7d2ca693e2ba03ba04fc44faa0a6190c5f35d master    
git_repo_checkout_branch "../filecopyex3"                         b110792500187b2af0223f8d09c66b4458c826e6 master    
git_repo_checkout_branch "../filesystem"                          e4e41b0301e15b9d53a7208ce0d5c0a1fa9ef7ef master    
git_repo_checkout_branch "../FIt-SNE"                             47ff14f1defc1ff3a8065c8b7baaf45c33e7e0b2 master    
git_repo_checkout_branch "../fityk"                               1a02b51e6fdacf19ac0209567e079064528057cc master    
git_repo_checkout_branch "../flac"                                cfe3afca9b3f27f0877203570705e072f0981b2e master    
git_repo_checkout_branch "../flann"                               f9caaf609d8b8cb2b7104a85cf59eb92c275a25d master    
git_repo_checkout_branch "../flare-floss"                         b5590ea4a36870bc4f0f2e61608a30d959575df3 master    
git_repo_checkout_branch "../flashlight"                          a3bcf633af5d8859e7615a5364f3c8c4de2a8ccb main      
git_repo_checkout_branch "../flat.hpp"                            a01021835185a6fa60d2e22dd4ff54f24b5bc78c main      
git_repo_checkout_branch "../flat_hash_map"                       2c4687431f978f02a3780e24b8b701d22aa32d9c master    
git_repo_checkout_branch "../flatbuffers"                         e3a3ea99f5d5c52f6e6220fe7092bd7f25e70757 master    
git_repo_checkout_branch "../flatton-offline"                     b40c1299102ef30b8d7effb6096e179c6f13904e master    
git_repo_checkout_branch "../flinng"                              d216121c8dd4db53631aac4d81feceb3859b50aa main      
git_repo_checkout_branch "../flip"                                580b2f65dcf622786c366f10cd9898ab07887cc5 main      
git_repo_checkout_branch "../float_compare"                       3c54f1a77a4d34cb20730436fd6217e0be701196 main      
git_repo_checkout_branch "../fluent-bit"                          7de2c45227468b51d6337141efbe2827dc48ea5f master    
git_repo_checkout_branch "../fluxsort"                            f0e584c2b8898b8c58df7aae4ca352c6fd500800 main      
git_repo_checkout_branch "../fmath"                               729563abd2a41fbda37e99e3b7f60e6f186b09fa master    
git_repo_checkout_branch "../fmem"                                b73b3d8b570c2f79df5a0b071efba392a82ddcd7 master    
git_repo_checkout_branch "../fmemopen_windows"                    b57cad19f19f413e56594f145c6fe2379cf19d60 master    
git_repo_checkout_branch "../FM-fast-match"                       3150e54b33fa90061213a9d31e0b91445cd58433 master    
git_repo_checkout_branch "../fmt"                                 96cb3516ddb3fb84de06949c9d6e7e81db22a793 master    
git_repo_checkout_branch "../fmtlog"                              57923b7f866bb6fc4bd8a0c886045af55c83d807 main      
git_repo_checkout_branch "../fnmatch"                             1010a28b0bc0d5667b41e7cc9e6e2116f743ec5c master    
git_repo_checkout_branch "../folly"                               2a35ad5ccb5e289ab61384f95080782923d76196 main      
git_repo_checkout_branch "../fontbm"                              98f9c2fdeac9ebe7c84da46cee6b63f24cc98b1d master    
git_repo_checkout_branch "../fontconfig"                          ef81472fe9afb32df6bf7a73b3584552725f5449 main      
git_repo_checkout_branch "../fontview"                            b8f4b51aa5f98eea3de785b9d12ae3271b5febc4 main      
git_repo_checkout_branch "../fph-table"                           6c245f09c6d767e00b8f8fcd8f33546b44415544 master    
git_repo_checkout_branch "../fpng"                                7298d34590a00921df8c0305869e9143e400a1bb main      
git_repo_checkout_branch "../FreeFileSync"                        94141bce764a6b7224e08283adfebb26f3da2f1b master    
git_repo_checkout_branch "../fribidi"                             75f438ed5f78ba6d5684b9e5c5aff8e83e4c4050 master    
git_repo_checkout_branch "../friso"                               b1808a4716dd07948154f3c8239ed34372dd0446 master    
git_repo_checkout_branch "../frozen"                              44deb2c2cf4d589199780891eb10e5b11c5b9dd1 master    
git_repo_checkout_branch "../fsst"                                ef52cb324a661e4e76e5eff10ac6452232d852c0 master    
git_repo_checkout_branch "../fswatch"                             ba411e0d0fabcd5cbf0881f1380482e2f5ab9f47 master    
git_repo_checkout_branch "../fuzzy-match"                         90f76b6455f40b206110eb79c9bf21a96f4673dc master    
git_repo_checkout_branch "../fxt"                                 4ee05de71cd944b8aca85f8682099c521cb57d26 master    
git_repo_checkout_branch "../g2o"                                 9c0ace64328b5adc059d4b2b89b054b4e2baa657 master    
git_repo_checkout_branch "../g3log"                               dc3e29e4293cc284d1818084899260ebc8c01780 master    
git_repo_checkout_branch "../gbenchmark"                          6159b23612f8a6e4ee3306fcf25c186667cee979 main      
git_repo_checkout_branch "../gcem"                                44e21766c080c963c90c50ea09ef5e9feea9ed0c master    
git_repo_checkout_branch "../gdbm"                                0abc1f52efa79611978660baa9b78bac7fcb4576 master    
git_repo_checkout_branch "../gegl"                                652eec36a420eaf4d03dc5652012b37b37b9af8e master    
git_repo_checkout_branch "../gencolormap"                         202b7f6478a39e10f9108214deca8526f27cd49e main      
git_repo_checkout_branch "../genieclust"                          5f049495becbac919792730ed3a40e046b154135 master    
git_repo_checkout_branch "../getopt"                              386a8bf960cdc1e49d1d2ffe7d6c25735d4bf18d master    
git_repo_checkout_branch "../gettext"                             480b17adc70964fe2d5f986f82a050df729094b0 master    
git_repo_checkout_branch "../gflags"                              9fa13f8bf74e8e06bf7938a994ecf2d8f305353f master    
git_repo_checkout_branch "../gibbs-lda"                           16a63a269238d3f0c8abc9c1aea23549becc0552 master    
git_repo_checkout_branch "../giflib-turbo"                        81f7044c4d7b2782d3e1645fffe15a49548b9c87 master    
git_repo_checkout_branch "../glaze"                               e1b22a2801f9428ad75a0127605e54bcb589cbcc main      
git_repo_checkout_branch "../glfw"                                dcab5668460b210713b80e25229e4f027f6b410f master    
git_repo_checkout_branch "../glib2"                               eaa6a65fc38809f683d563a3eefb5da131f82ad2 main      
git_repo_checkout_branch "../glm"                                 45008b225e28eb700fa0f7d3ff69b7c1db94fadf master    
git_repo_checkout_branch "../glob"                                6101cee85bb8aadfe30125cf91c68d5191571fcc master    
git_repo_checkout_branch "../glog"                                8ede87dcf3af20b2ce6102bd57094b9cf319a411 master    
git_repo_checkout_branch "../glyph_name"                          eaeca7bf840b5da21e3a5458815861e48691cdf5 master    
git_repo_checkout_branch "../gmic"                                7523c47db730ab5ce1b825e815f1719e013c5b8c master    
git_repo_checkout_branch "../gmic-community"                      0f33b861029dc83a04b27105f14bbd3c3b68afdc master    
git_repo_checkout_branch "../GMM-HMM-kMeans"                      df76ebd12cb9902705569a17a6a19f02835b8516 master    
git_repo_checkout_branch "../GMMreg"                              b18d1c9cec54ce84df950f5821b24b8e4d03d519 master    
git_repo_checkout_branch "../gmt"                                 1100c78fd5c38e4c5d02ff12ce132325db55addc master    
git_repo_checkout_branch "../gnuplot"                             861e08fcd6676c555c825f3fa970c2d0c2ce8177 master    
git_repo_checkout_branch "../gnuplot_i"                           d681146db50554f2d51be40e058c5c1a1917b7b6 master    
git_repo_checkout_branch "../gnuplot-palettes"                    d6f7e3a8e70ae8e81b5c153dc0f6bdd8ffde4814 master    
git_repo_checkout_branch "../GoldFish-CBOR"                       4ba6a01c7714fee78ce311ef8910f2065e80c8a5 master    
git_repo_checkout_branch "../google-diff-match-patch"             62f2e689f498f9c92dbc588c58750addec9b1654 master    
git_repo_checkout_branch "../google-marl"                         add2bdbc345e799870891e2897453b951c2461f1 main      
git_repo_checkout_branch "../googletest"                          69303291656d627980aa6352efaa016d98cabcc9 master    
git_repo_checkout_branch "../gperf-hash"                          bb49297b10641b145da16dea79061cca593f57e3 master    
git_repo_checkout_branch "../GQ-gumbo-css-selectors"              a00f4ed73064797c627887d5be7b8bee41d7223f master    
git_repo_checkout_branch "../gram_savitzky_golay"                 304eacc1984e9bfe19a700a577bac14213de3521 master    
git_repo_checkout_branch "../GraphBLAS"                           6680f9f5058f0afdb1730429867f2baec07a3b92 stable    
git_repo_checkout_branch "../graph-coloring"                      8d0716b3d4f61f5388d31f3356ba85ce867199da master    
git_repo_checkout_branch "../GraphicsMagick"                      a0d97e463fa59377af92f34ba86751b78f5ae1eb master    
git_repo_checkout_branch "../graphit"                             2e0149719b10484ae4caf99257fa9448bc1aa9a9 master    
git_repo_checkout_branch "../grok-jpeg2000"                       325f483dcf202c3305e28a5ff958a29ce73b09a3 master    
git_repo_checkout_branch "../groonga"                             75ccbc537159ffc7928b0a77a77ecb3414f1f919 master    
git_repo_checkout_branch "../GSL"                                 b39e7e4b0987859f5b19ff7686b149c916588658 main      
git_repo_checkout_branch "../gtl"                                 e2cafcbc52d7799bceb5eb67a6003aa7bdf7533e main      
git_repo_checkout_branch "../gtn"                                 568d35665fcf15e61df53524f53f7b348523e990 master    
git_repo_checkout_branch "../gtsam"                               0fee5cb76e7a04b590ff0dc1051950da5b265340 develop   
git_repo_checkout_branch "../guetzli"                             214f2bb42abf5a577c079d00add5d6cc470620d3 master    
git_repo_checkout_branch "../guile"                               92d02b66f5905be4acb66746d09c0d03805973e2 main      
git_repo_checkout_branch "../gumbo_pp"                            9280d57ade576944dcd9c016b2ff216b755ab65d main      
git_repo_checkout_branch "../gumbo-libxml"                        4003ca5e388169b2bb4e650599153b8075f30afd master    
git_repo_checkout_branch "../gumbo-query"                         3326ef902db3e90144eee5cd83e4a4c9638e7958 master    
git_repo_checkout_branch "../h5cpp"                               1444cf87cc2953c473129eeb2217b483aa4ffcc1 master    
git_repo_checkout_branch "../Hackers-Delight"                     8b8407a7168b6e16a53b0072e48620cdb346cd76 master    
git_repo_checkout_branch "../half"                                0f5cb7dcaedcf35520df4ebb49f87dfd9c4fec4f master    
git_repo_checkout_branch "../harbour-core"                        1419e9af12724685dc2cd26fdfdccc93d754bc2e master    
git_repo_checkout_branch "../HashMap"                             277a179b64389bbde64623f5b73cb6ce06b01a48 master    
git_repo_checkout_branch "../HDiffPatch"                          752d9895ff679300fb1719ef184237f2f2ec2d12 master    
git_repo_checkout_branch "../IconFontCppHeaders"                  778a12759ba9100f24a02efce5f2f95da89ea8a1 main      
git_repo_checkout_branch "../IdGenerator"                         e06fc2db9379a68269021f3460464d06fde59eb8 master    
git_repo_checkout_branch "../ImageMagick"                         f54cff4648f6bbef35bdf249d7ccedd4be6f7f63 main      
git_repo_checkout_branch "../Image-Smoothing-Algorithm-Based-on-Gradient-Analysis" c2e244bd503c5bb161eff43c1af95edcca1029e4 master    
git_repo_checkout_branch "../Imath"                               e54e953d33ff765e1693bc7d1a8b7a609a6340a7 master    
git_repo_checkout_branch "../IMGUR5K-Handwriting-Dataset"         94714f601790ca9b73cfec78c901aae6147af512 main      
git_repo_checkout_branch "../InferenceHelper"                     7c975cf9d32016aa6bfceabf6922fe6d808dc5eb master    
git_repo_checkout_branch "../InversePerspectiveMapping"           911dbbe51f4c3ffcf7ba7484b3c5a60dcd6325a2 master    
git_repo_checkout_branch "../Ipopt"                               261e3fd486816559f8006612a4519af101aaecc2 stable/3.14
git_repo_checkout_branch "../ITK"                                 52892f053b38698da0de317762d6b20db05699a6 master    
git_repo_checkout_branch "../JabRef-abbreviations"                fff00f8aa657d89d70995ce85ba48bfe78f19489 master    
git_repo_checkout_branch "../JabRef-Browser-Extension"            d59068bd2114f52d4767b7ef7e7a74a75f7303c6 main      
git_repo_checkout_branch "../JamSpell"                            1ece237a89b75a018b9e3093e7213bd0a112cb47 master    
git_repo_checkout_branch "../KDSPDSetup"                          28a072989af3d08f17195fb883c6467331443cc8 main      
git_repo_checkout_branch "../K-Medoids-Clustering"                71d36238e376c8be18a58582cfd0247b679f93ea master    
git_repo_checkout_branch "../L1Flattening"                        f7e7a87fb54bcf22c711bb8282bc6f9749dbcb7e master    
git_repo_checkout_branch "../LBFGS-Lite"                          a96c50e3fdf8b5278577522a2c5e75766c8670bb master    
git_repo_checkout_branch "../LDCF-hash"                           e5c1dacc8dc0d13568d908e2d38e6f37f2c8ef72 master    
git_repo_checkout_branch "../LeptonicaDocsSite"                   ac9a10ed893db6c37dc339c158368bb7997a1dc9 gh-pages  
git_repo_checkout_branch "../LightGBM"                            3e9ab53c7d0c03258c947b34d99669c5bb887525 master    
git_repo_checkout_branch "../LightLDA"                            0f78696f58db56aa7e41f65b0b44c47dfaf27552 master    
git_repo_checkout_branch "../LightLDA/multiverso"                 3c03cce205c3eb33ebf83b417ac0748daa9efdd1 master    
git_repo_checkout_branch "../Lightning.NET"                       fdd8b310778b5f1a63af4ed144260dfc7ef0b39e master    
git_repo_checkout_branch "../LLhttp-parser"                       8c306b190ecf6c3a345bf7473d9eeee446fd994e main      
git_repo_checkout_branch "../LMW-tree"                            bc9ea4d351cca1378b24e28ff0d261fd77c0f20c master    
git_repo_checkout_branch "../LSWMS"                               584ff87ba41defb5a2b12553495dca1d73ae663c master    
git_repo_checkout_branch "../LZMA-Vizualizer"                     3eeb57563b84d262785bff57621ca92675781c6e master    
git_repo_checkout_branch "../MariGold.OpenXHTML"                  e5fc8e210dda6ce042e04eeb162f8a53de043754 master    
git_repo_checkout_branch "../MegEngine"                           3b1a1d0ab201c415d6c1d4130be0c0bb11fd7bf4 master    
git_repo_checkout_branch "../MetBrewer"                           8f06216764633854ba668bb52fc8db053675276e main      
git_repo_checkout_branch "../MicroPather"                         33a3b8403f1bc3937c9d364fe6c3977169bee3b5 master    
git_repo_checkout_branch "../MITIE-nlp"                           42dbcd5dad55e9d5bc76580fc9582097342d9916 master    
git_repo_checkout_branch "../MNN"                                 0044fdcbd0a6e731115a491a7e128af603cfabee master    
git_repo_checkout_branch "../ModernCppStarter"                    57d0b4dfc8db967030e0760ddd2b37a3faaf4870 master    
git_repo_checkout_branch "../MPMCQueue"                           b9808ede08f26fa9df4df4e081d19cace8f6c6ea master    
git_repo_checkout_branch "../Multicore-TSNE"                      c1dbf84eb550980876d8ed822af4e9dfd21c5e05 master    
git_repo_checkout_branch "../MultipartEncoder"                    ab4182accd6e69128dd3cbc20c1c08f921b86be0 master    
git_repo_checkout_branch "../NanoLog"                             2a94d70f9d1db4da416053b1b926387fa068a59b master    
git_repo_checkout_branch "../NiuTrans.NMT"                        89add89fccdb66dc273b2267a8a4f26612ed4e87 master    
git_repo_checkout_branch "../NSISDotNetChecker"                   abbaae9a521a930b41242a029e8172bba2143eb5 master    
git_repo_checkout_branch "../NSISFileCheck"                       a59a42cde584f7f7bb1612790e38db6aa158e754 master    
git_repo_checkout_branch "../NSISMultiUser"                       949ebf7920500ee1266a246a3cd93548a581966b master    
git_repo_checkout_branch "../NSIS-OBSInstallerUtils"              7292d894ef16edfc6ed2dd89e7a9189c59bd6501 master    
git_repo_checkout_branch "../OfficeIMO"                           8ec711a3b69e6da1aad55ab0f6bf50559b9fa31a master    
git_repo_checkout_branch "../OpenBLAS"                            1978c964d064048bbc1386268fc3633427a83d42 develop   
git_repo_checkout_branch "../OpenCL-CTS"                          049ce662ecacc0ee5e311d89762e6ee7e42c4e0a main      
git_repo_checkout_branch "../OpenCL-Headers"                      e90920bffaf7046c294151a97900f5ef87b97af6 main      
git_repo_checkout_branch "../OpenCL-SDK"                          78e494f824d0dbe9279c4693ab1d2d807d29ac96 main      
git_repo_checkout_branch "../OpenColorIO"                         732accc53d7a0aeff36504665b7b8b814b8cf8fb main      
git_repo_checkout_branch "../OpenCP"                              3862d72230e429bb9a6030b1da2428b21b545bdb master    
git_repo_checkout_branch "../OpenEXR"                             78ce679a70182b745a79d6df19c31cbd652e49f4 master    
git_repo_checkout_branch "../OpenFST"                             0e2ebdf25ee26656570947ea72e149b5216424ac master    
git_repo_checkout_branch "../OpenFST-utils"                       62b8cf42b309873e2e9433d3329a631ff46f2547 master    
git_repo_checkout_branch "../OpenNN"                              eecfed7eb1531bd947acefa6851d2b3f02b1df7d master    
git_repo_checkout_branch "../Open-XML-SDK"                        6bf2a1c68edbb54689511a7ec20080e2e106de6a main      
git_repo_checkout_branch "../OptimizationTemplateLibrary"         bd9c4193e6354e9974488cf98f5ddf4f01e2d1fe master    
git_repo_checkout_branch "../OTB"                                 286177dbbfb19f983339fe3d44e77cfb40629acd develop   
git_repo_checkout_branch "../OZBCBitmap"                          8e7618151f57dcf7ac96e8e24879c715f481b7bf master    
git_repo_checkout_branch "../PaddleClas"                          231de43cddb4ae0870870eab889c347468d36404 release/2.5
git_repo_checkout_branch "../PaddleDetection"                     2d3517aa0b8adeec2752db2411c61ee56ec5a0af release/2.7
git_repo_checkout_branch "../Paddle-Lite"                         7aa1db7ef59ddce98c57c161fbf7e0918482c468 develop   
git_repo_checkout_branch "../PaddleNLP"                           b36b6a01a6dd65ea45f4e8db0177a61c80ae410e develop   
git_repo_checkout_branch "../PaddleOCR"                           6ed5562cedce18f0313d3b83271986dd6c136871 release/2.7
git_repo_checkout_branch "../PaddlePaddle"                        df6ed707a1f9331d445e2ede7fccd6f333a52ee9 develop   
git_repo_checkout_branch "../PDFGen"                              53ea781d446d51ce70492a796c2523286490633f master    
git_repo_checkout_branch "../PEGTL"                               68f446153c5c736035dbee1286e788f904006add main      
git_repo_checkout_branch "../PGM-index"                           f578e68414c60f9869c5611575143645f75e0ce1 master    
git_repo_checkout_branch "../PhotonLibOS"                         e395bd577b4eb8cac5c2d7d3f17cb60b7be3c5d9 main      
git_repo_checkout_branch "../Pillow"                              b64a4f28a648e095679dfbc7272465cd3c890027 main      
git_repo_checkout_branch "../PlatformFolders"                     62566ad085c8414d20febed1a3b1004118ded7ed master    
git_repo_checkout_branch "../PNWColors"                           f16a14fcb0a1f93741e1acec221ce6391d93f0fa master    
git_repo_checkout_branch "../QALSH"                               33101fdcd4861093e74e2d12d1a5409c0e2af571 master    
git_repo_checkout_branch "../QALSH_Mem"                           c3e92ae7784fa6f5b62cc5dd2c0dc597e276f8a0 master    
git_repo_checkout_branch "../QCBOR"                               cbd7d138669f4e19d6e06443c3e3bee44cc342ac master    
git_repo_checkout_branch "../QuantLib"                            b9d94cad2d6eb0bb74621d2644e342a6a6aa26c7 master    
git_repo_checkout_branch "../QuickJS"                             669df99ba91c96fc9e82c7ee8720e24a5511b0ff master    
git_repo_checkout_branch "../QuickJS/test262"                     a76ebd15fb52e36c32e995d5c9ce573b800a3a23 master    
git_repo_checkout_branch "../QuickJS/thirdparty/uint128_t"        fe5fb0600369c8b662cb13eba45b1140f416e93d master    
git_repo_checkout_branch "../QuickJS-C++-Wrapper"                 54db47bb4b048c28cbb8d50e7d7d9feda0ad4ff5 master    
git_repo_checkout_branch "../QuickJS-C++-Wrapper2"                7e3099549c927911a911a89decf15fd8ab498a1c master    
git_repo_checkout_branch "../RAKE"                                22474be2ba9a88d78ea2f2efd8d1f8115af869e1 master    
git_repo_checkout_branch "../RandomizedRedundantDCTDenoising"     0a42da0e3ee9056ccd21344f6792c2ca5fa41f1f master    
git_repo_checkout_branch "../RapidFuzz"                           cb8a1b112ab38d1b1119abb36de7c621bd47322a main      
git_repo_checkout_branch "../RectangleBinPack"                    83e7e1132d93777e3732dfaae26b0f3703be2036 master    
git_repo_checkout_branch "../RE-flex"                             9c68508dd6d775dda3ba147d42dc26a045717638 master    
git_repo_checkout_branch "../RNGSobol"                            57ac5551234270dd146d39fb98045093b3898948 master    
git_repo_checkout_branch "../RoaringBitmap"                       939748f6864deaace54e724f28b6b484dd56f03b master    
git_repo_checkout_branch "../RRD"                                 83a33321fd476701fb7972d85df62a4f5e8e7bc2 master    
git_repo_checkout_branch "../RRPN"                                bc7ed8490c58ffe4c1502cf1f370c8d916eb94b9 master    
git_repo_checkout_branch "../RuntimeCompiledCPlusPlus"            c77c6b83cf9e8143050ccf4914ad75ae2767c975 master    
git_repo_checkout_branch "../RxCpp"                               5f144832f175408840a2bd403dafab497c772dd3 main      
git_repo_checkout_branch "../Sancho.Panza.on.tesseract.OCR"       4bd1a89621b6da92836a25334f55a94c43ec7741 main      
git_repo_checkout_branch "../ScriptX"                             894fd81ebb1258b37fb14e9b636d4d9eae81835a main      
git_repo_checkout_branch "../Sealighter"                          654306da02552c9728b66a71545210b5d0d8d2ae main      
git_repo_checkout_branch "../SFML"                                267bbe35b80f946c3b676a2dbd7577a973b99efe master    
git_repo_checkout_branch "../ShapeCrawler"                        b0ec9e2a3b0a39325c11f23c68311fda408728b0 master    
git_repo_checkout_branch "../SheenBidi"                           e667eb3a63ee704194f8d94834d8e12b18db5b21 master    
git_repo_checkout_branch "../Sherwood"                            f122548caec2a19b15139c9f46b314a8a5572a1b master    
git_repo_checkout_branch "../Shifted-Hamming-Distance"            49836770d8c45be24abb9c9358b440b4087af72c master    
git_repo_checkout_branch "../Signals"                             17881fb92ec314bb43549cc2cc8acfac24916f91 master    
git_repo_checkout_branch "../SilkETW"                             093f57201525343d4ebd3d9be33f4c6a1a425ed5 master    
git_repo_checkout_branch "../SIMDString"                          fda47507588dc60b7800512e4c59909d8326fe99 main      
git_repo_checkout_branch "../SipHash"                             f26d35e964c6290ffe23d9043475ad3129f409e0 master    
git_repo_checkout_branch "../Solo"                                1ff887302782c25b8f57f22cc141560f7b1bdf1f master    
git_repo_checkout_branch "../Sophus"                              d270df2be6e46501b1e7efc09b107517e0be0645 main-1.x  
git_repo_checkout_branch "../SPSCQueue"                           1053918dbd251fbff69b24ef27fa5d51c29ec2af master    
git_repo_checkout_branch "../SQLiteCpp"                           7df94cd2a8628cdbfd218b537a9f8f0af2e47afb master    
git_repo_checkout_branch "../SQLiteHistograms"                    4d316cf0466e57e40fec50bbfc753af63d330025 master    
git_repo_checkout_branch "../SSIM"                                2e6a16c48fdda1df4b40726f4f09c3dd552f2141 master    
git_repo_checkout_branch "../StarSpace"                           8aee0a950aa607c023e5c91cff518bec335b5df5 main      
git_repo_checkout_branch "../StringViewTests"                     7e2e4c4f17dda2ed4569cca409fa2f02e0ef77ad master    
git_repo_checkout_branch "../StringZilla"                         91d0a1a02faae90a41c60a30855d5935eb3eaef1 main      
git_repo_checkout_branch "../StronglyUniversalStringHashing"      a80e04fc75d34885b5c31ae714c4f24e5ea49be9 master    
git_repo_checkout_branch "../SuiteSparse"                         31bdd56256b3d2a7dffaade1fbd074d48489865c dev       
git_repo_checkout_branch "../SuperString"                         6c4a6ceb5bda38324876bf7d82d872ca14adf7b6 master    
git_repo_checkout_branch "../SymSpell"                            32ae4815ad5b4622fc1e9931da37c70117c86b27 master    
git_repo_checkout_branch "../SymspellCPP"                         3f3258f5bdbc287d39782e97f520da16c7c4fe02 master    
git_repo_checkout_branch "../SZ"                                  f4667759ead6a902110e80ff838ccdfddbc8dcd7 master    
git_repo_checkout_branch "../SZ3"                                 f6cae37f557345889cc487e09147bf6aea450ff9 master    
git_repo_checkout_branch "../TelemetrySourcerer"                  553fbb132a02cfc8d051252312f9413b46888b3c master    
git_repo_checkout_branch "../ThreadPool"                          9a42ec1329f259a5f4881a291db1dcb8f2ad9040 master    
git_repo_checkout_branch "../TNN"                                 1c27f2000539870cbbc21f43e7978580f08f1685 master    
git_repo_checkout_branch "../TraceETW"                            60d14b82aad0066bbb097826d57fa0f86b3d5439 master    
git_repo_checkout_branch "../Turbo-Range-Coder"                   9f86090f83f0ec6660c2ce842f036fdadf8b35f1 master    
git_repo_checkout_branch "../UIforETW"                            3f33ef7207a7b9df2a4441d3b37e65ddcd274632 main      
git_repo_checkout_branch "../UnofficialLeptDocs"                  953b8a83b67a6f40f9d95b64b413062c2570e1da gh-pages  
git_repo_checkout_branch "../URI-Encode-C"                        21ad52e02f0cebb5e079f3d5666833cc894fa45e master    
git_repo_checkout_branch "../URL-Detector"                        368c4e4481714a7f9c271515131cbf0282759006 master    
git_repo_checkout_branch "../Verify"                              13dbd62c3198dc7d3736252b1def3c9a71821d85 main      
git_repo_checkout_branch "../VisualScriptEngine"                  f76564d795b08d413a8625edba87dff21837039f master    
git_repo_checkout_branch "../VQMT"                                e0dfe692c1712bd800f18dcedd2afdf4ffb3e474 master    
git_repo_checkout_branch "../VSNASM"                              6fa151d2735fb9a0a25169c1db4483e213edbc67           
git_repo_checkout_branch "../VTK"                                 35f5797da105cd53e12d1ea4faa72737650e149a master    
git_repo_checkout_branch "../WebView2Browser"                     ff5ef355ac16b285bdada10274c10685c7d1201a master    
git_repo_checkout_branch "../WebView2Samples"                     f51a817e0c5b941400f8da5cb1efedc1d3208c35 master    
git_repo_checkout_branch "../Win32_read_directory_changes"        bcbd3c486c2bad01a2f851b2018427ad60620018           
git_repo_checkout_branch "../Win32_read_directory_changes_IOCP"   4e43c796c3bd076a90d25d936ebbb8748eca1dc7           
git_repo_checkout_branch "../Windows10EtwEvents"                  8a8a66f7a4becc0cabaa1640d4e874f7a75af3da master    
git_repo_checkout_branch "../WinHttpPAL"                          590c28949f50004911d4d22b1e328433355351f1 master    
git_repo_checkout_branch "../WinToast"                            a78ce469b456c06103b3b30d4bd37e7bb80da30c master    
git_repo_checkout_branch "../XMP-Toolkit-SDK"                     4950ddd722cafbd92df32f754837f71946fc9d5c main      
git_repo_checkout_branch "../Xoshiro-cpp"                         19bcbb2ce0ed158233187f524fd0964c105a65b3 master    
git_repo_checkout_branch "../YACLib"                              a7fd400f614a71ba3e0f4888cf09c196c5c46d02 main      
git_repo_checkout_branch "../ZLMediaKit"                          5b5422fc075d8486d163f4a5d6107912f05955e0 master    
git_repo_checkout_branch "../ZQCNN"                               5f4eb9adc5c98e667eba1c8783a6db69f7aee706 master    

# --- all done ---

popd                                                                           2> /dev/null  > /dev/null

